### ISSUE TITLE
Delete doesn't.

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-webui#1001]
**Describe the bug**

The dialog text when you "delete" a file has warnings about permanent irreversibility, however:

1. After deleting from web UI, the file on my filesystem is still there.

2. If I re-add the same file after deleting in web UI, I'm at exactly the same state as before I deleted it.

Nothing is deleted, and the action is impermanent and reversible.

We should change the language to describe what's happening in a more correct and also less scary way.

**To Reproduce**
1. Go to the Files section in web UI
2. Drop a file there
3. Click the '...' and click "Delete"
4. Click the "Delete" option in the confirmation dialog
5. Check filesystem (file is still there)
6. Drop same file on the screen again (re-adding)

**Expected behavior**

File would be deleted, and re-adding would result in a different hash... I mean, not really, but the language makes it sound like this is what would happen!

**Screenshots**

<img width="535" alt="Screen Shot 2019-04-05 at 4 06 47 PM" src="https://user-images.githubusercontent.com/50103/55661052-70d63500-57be-11e9-9385-db3f9d8d97ad.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: NA
 - Version: NA

**Comment by olizilla** [comment]
Fair point! Are you up for helping craft a less scary message? How about:

> The file will be deleted from your IPFS repository. There is no option to undo this action, but if you still have the orginal you can add it back again to restore it. 

> If the content is available on other nodes, either because you shared it, or it was independently added, deleting it means you will no longer be hosting it but it will not remove it from the network.

**Comment by SgtPooki** [comment]
I assume this text was updated at some point to address this issue. The "delete" option no longer exists and is "remove" instead now.

Prompt reads as:

![image](https://github.com/ipfs/ipfs-webui/assets/1173416/2c573a36-65b5-430d-a5bb-8620df88191e)
