### ISSUE TITLE
Provide an IPNS link to the webui

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-webui#1032]
**Is your feature request related to a problem? Please describe.**
The fact that https://webui.ipfs.io/ can be down

**Describe the solution you'd like**
An IPNS link

**Comment by olizilla** [comment]
It's not ideal as it's based on DNS and a DNSLink, but there is an IPNS address for webui at

`/ipns/webui.ipfs.io`

The DNSLink is updated when a PR is merged into master on this repo.

```console
$ ipfs resolve /ipns/webui.ipfs.io
/ipfs/Qmc9PdUBnynhk2nc8jfnVwamhTpNfeDAhNV3MRwkDa84yR
```

**Comment by hazae41** [comment]
How about generating an IPNS hash for the webui?

**Comment by kartezjusz** [comment]
CZYTAJ OPIS ZANIM BĘDZIE ZA PÓŹNO-
porównaj numery z tego opisu z numerami z ogłoszeń
Piotra Piasty Wrocław PIOTR WALDEMAR PIASTA „DIGITAL SYSTEMS” Wrocław al. Poprzeczna 66/6 ul / al Manganowa 27/7 (7/27 na przemiennie) dane z CEIDG NIP-8951647389 kryptokoparki24.pl Telefony: 600465412, 796745805, 574517679, 796051081, 574143177, 576904953, ksywy= Kartezjusz Kowalski, Peter Kowalski, Piotr Kowalski, Piotr Nowak. meile jakich urzywa walt666 kartysim1 kartysim2 mbtpozew  loginy: walt666, WUPE Właściciel stron sprawdz-numerek.pl, czyjnumerek.pl i wszyscy ci na których są opinie na temat jego tematu.
Odradzam jak w celach zleceniobiorców i sprzedawców, chyba ze chce się wzbogacić o stalking internetowy.


Pan gotów jest sam zrujnować osobę, instytucję oraz wykonana prace, nie przestrzegać żadnych zasad etycznych, handlowych  czy zaleceń eksploatacyjnych jako klient a potem nie da wam żyć i wykorzystując KONTAKTY u administratorów stron internetowych (allegro,oferia,youtube) i znajomości w branży IT i mając parę stron internetowych w tym sprawdz-numerek.pl i czyjnumerek.pl na fałszywe pozytywne opinie pisane przez siebie, fałszywe dane oraz zagraniczne serwery będzie uporczywie nękał i szkalował w internecie Was, Wasze firmy, rodziny i dzieci, dzwonił nocami z prywatnego, latał dornem pod domem robiąc zdjęcia, wstawiał przez boty setki negatywnych opinii, kręcił filmy z ukrycia i publikował je w internecie, wstawianie numerów telefonu w anonse erotyczne, rejestrowanie waszych adresów meilowych na portalach zagranicznych śmieciowych, wysyłanie na meila wirusów,linków z wtyczkami aby się dostać do danych z komputerów jak i telefonów, wysyłanie listów,kurierów, sms stosował szantaż i wszelkie krętackie metody by zmęczyć was psychicznie, bo na rozstrzyganie spraw w sadzie lub inny cywilizowany sposób jest za cienki. Gość to materiał i dla prokuratora i dla dziennikarza i psychiatry (ale od tego ostatniego to ma klinikę zony Moniki)


A tak Wygląda, to jego aktualne zdjęcie z lokalnego przewodnika google(należny skopiować link i wkleić do przeglądarki): images.app.goo.gl/xDnHHR3AfKHcDosE7
Poszukuje osób które w ten sam sposób są nękane lub poszkodowane (temat pobierania pieniedzy za rejestracje kart i nie wysylanie towaru) prosze o kontakt: pozew_na_kartezjusza@o2.pl
Pomoc prawna bezpłatna.
