### ISSUE TITLE
UX: Use a service worker

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-webui#1044]
Using a service worker (https://developers.google.com/web/fundamentals/primers/service-workers/) will enable 3 major user experience issues

## Issue 1: offline experience
The local webui can't be loaded if ipfs is not started

## Solution 1: service worker caching
Being able to load the webui and see "not connected" even if ipfs is not started, by using a service worker

## Issue 2: notifications
We need to use an extra extension (ipfs-companion) to receive notifications when ipfs in online or offline

## Solution 2: service worker communication & background sync
The ipfs-webui could push notifications like "connected to ipfs" or "your file is now available on ipfs.io gateway":
- even if the browser tab is not visible (using service worker communication)
- even if the browser is actually closed (using background sync inside the service worker)

## Issue 3: desktop installable
Make the webui installable on the desktop 

### Solution 3: Progressive Web App
Using a service worker would make the webui recognized as a Progressive Web App (https://developers.google.com/web/progressive-web-apps/) 
As a result, it could be installed on the desktop with any browser that supports PWAs (e.g Brave browser)

**Comment by olizilla** [comment]
I'm generally in favour of this. I enabled the standard create-react-app service worker on ipld-explorer... it just means you need to add some UI to inform the user when there is a newer version and nudge them to refresh.

I'm less sure about browser notifications... I generally turn them off on any site that asks for them.

Being able to install webui as a PWA would be cool, but we'd generally recommend installing ipfs-desktop as it can manage updating your `ipfs` commandline tools too.
