### ISSUE TITLE
Ability to set custom public gateway

### ISSUE THREAD

**Issue by jonaharagon** [ipfs/ipfs-webui#1074]
I'd like the ability to define a custom gateway in the settings like you can with the IPFS Companion browser extension, so the link copied when a file/screenshot is shared or when "view on IPFS gateway" doesn't have to be from `share.ipfs.io` or `ipfs.io` respectively.

**Comment by shazz** [comment]
Hi,

Or is it possible, to support private swarms, to have the "View on IPFS Gateway" url configurable? 
In my case it would be great if it could point to my local gateway

Thanks !

**Comment by lidel** [comment]
Continued in https://github.com/ipfs/ipfs-webui/issues/1717
