### ISSUE TITLE
Support Import from IPNS Paths

### ISSUE THREAD

**Issue by DeedleFake** [ipfs/ipfs-webui#1076]
**Is your feature request related to a problem? Please describe.**
I've got DNSLink set up with one of my domains and I use it across multiple machines. If I want to add files to it through the WebUI I usually just add the domain as a directory in Files, modify it, and then update the DNSLink to the new hash. When I add the domain to Files, however, it only accepts hashes. Trying to enter `/ipns/fake.example.domainname` doesn't work.

On a similar, but more minor, note, the bar at the top for entering hashes to get information on also doesn't support IPNS.

**Describe the solution you'd like**
Entering `/ipns/fake.example.domainname` should automatically resolve the appropriate hash and _then_ fail if it can't resolve it, rather than simply not working at all.

**Describe alternatives you've considered**
I generally run `ipfs resolve /ipns/<domain name>` manually to get the hash, or I go to the domain in a browser and copy the hash manually.

**Additional context**

Trying to add something to Files:

<img width="473" alt="Screen Shot 2019-07-29 at 12 52 13 PM" src="https://user-images.githubusercontent.com/326750/62066639-ca47f100-b1ff-11e9-8a86-b51139abb5eb.png" />

Trying to get information about an entry:

<img width="766" alt="Screen Shot 2019-07-29 at 12 52 21 PM" src="https://user-images.githubusercontent.com/326750/62066663-d3d15900-b1ff-11e9-916f-b40a5db6daf7.png" />

**Comment by hsn10** [comment]
Yes, Add to MFS from /ipns/ will save me a time during my daily workflow. Its important enhancement.

**Comment by SgtPooki** [comment]
closing in favor of https://github.com/ipfs/ipld-explorer-components/issues/400
