### ISSUE TITLE
Cannot add folder using IPFS GUI on macOS

### ISSUE THREAD

**Issue by bixu** [ipfs/ipfs-webui#1154]
**Describe the bug**
I'm unable to use the "+ADD" button in the IPFS GUI on macOS Catalina.

**To Reproduce**
See attached video

**Expected behavior**
I expected to be able to add a new folder for IPFS-shared content.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina Public Beta

[cannot_add_folder_to_ipfs.mov.zip](https://github.com/ipfs-shipyard/ipfs-webui/files/3596587/cannot_add_folder_to_ipfs.mov.zip)

**Comment by alexwykoff** [comment]
I believe the problem may not be isolated to MacOS. 

I am able to replicate on Windows 10 using the IPFS desktop app (revision c0cf2b8).

**Comment by dogancelik** [comment]
I have the same problem on Windows 10, desktop app revision 1eef40c9f8bf5c135f21fd80ae739405ff6da8e9

**Comment by SgtPooki** [comment]
This is no longer an issue. I was able to add a new folder using the add folder button today using Version 0.21.0 (0.21.0)

<img width="262" alt="image" src="https://user-images.githubusercontent.com/1173416/174672686-026f35bd-c0bc-486e-8c55-0b89d7afc1eb.png">
