### ISSUE TITLE
feat: improve repo size labels and explanation

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1248]
> cc https://github.com/ipfs-shipyard/ipfs-webui/issues/1042, https://github.com/ipfs-shipyard/ipfs-webui/issues/629

MFS can store files in "lazy" fashion, which means root is added to MFS, but children are fetched lazily, on first use.

### Example

English wikipedia mirror is ~650 GB. Lazy pointer to it can be added to MFS instantly via:

```console
$ ipfs files cp /ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco /en.wikipedia-on-ipfs.org
```

### Problem

This feature of MFS creates a problem in WebUI, it looks like "Files" take more space than "entire repo":

> ![Screenshot_2019-10-11  cohosting full - Files - IPFS](https://user-images.githubusercontent.com/157609/66646212-d1d73d80-ec25-11e9-97f2-89e35eee2dbd.png)

This will become a problem when we start taking advantage of this lazy mode in website cohosting (discussed in https://github.com/ipfs-shipyard/cohosting/issues/6)

### Solution?

We need to change the labels, make them more informative.
Below is a quick mock that illustrates what additional information needs to be conveyed.
The problem is that it does not look good, and we need to clean this up somehow.

> ![Screenshot_2019-10-11  cohosting full - Files - IPFS(1)](https://user-images.githubusercontent.com/157609/66646210-d1d73d80-ec25-11e9-921a-3a9aeeeedbb4.png)

Thoughts?

**Comment by ericronne** [comment]
A few ideas which hopefully reflect the state of affairs accurately …

### A - Modify two labels
Change the third and fourth labels to "all blocks" and "local repo" respectively, to help explain why the "files" number might be larger.
![Artboard Copy 3](https://user-images.githubusercontent.com/9259185/66671955-c8000b00-ec22-11e9-9e15-078edd1e6868.png)

### B - `A` plus a hover-triggered explainer panel
Add a feature which offers the user text explaining more about the numbers
![Artboard Copy](https://user-images.githubusercontent.com/9259185/66672227-6f7d3d80-ec23-11e9-97c1-b10cb0a5139a.png)

### C - `A` plus a click-triggered panel
Similar to above
![Artboard Copy 2](https://user-images.githubusercontent.com/9259185/66672269-8885ee80-ec23-11e9-936d-adf24a5bff6f.png)

If B or C seem worthwhile and tests well (test? yes let's!), i'll design the full panel. If _none_ fit the bill, we can try something else …

**Comment by lidel** [comment]
I'd go with B or C: we _really_ need an explainer for these values. 
We already have a lot of whitespace on the top of Files screen,  so B may save space, but I have no strong feelings here.

@ericronne small clarification: value behind `blocks` is "the number of blocks" (I have over 600 000 of blocks in my repo).  The `all blocks` label suggests value represents total size used by blocks, but that value is already under `local repo`. Perhaps we should rename "pins" and "blocks" to something like `# of blocks` and `# of pins` to make it clear its not size, but a number of items?

**Comment by ericronne** [comment]
I wonder if simply removing `all` would help.

### B
![Artboard Copy](https://user-images.githubusercontent.com/9259185/66785493-0d327000-eea3-11e9-9c23-db458c7d7b31.png)

### C
![Artboard Copy 2](https://user-images.githubusercontent.com/9259185/66785492-0d327000-eea3-11e9-977e-c9da1c67726b.png)

**C** feels more user friendly to me, but creates slightly more visual noise.

**Comment by lidel** [comment]
Yup, dropping `all` is better :+1: I also would go with **C**, just for clarity's sake:
**B** introduces problem of having  ![2019-10-15--01-20-40](https://user-images.githubusercontent.com/157609/66788991-03802b00-eeea-11e9-95f2-3f27da169182.png) and  ![2019-10-15--01-20-59](https://user-images.githubusercontent.com/157609/66789005-0ed35680-eeea-11e9-975a-9911df18efc2.png) pretty close to each other.

**Comment by ericronne** [comment]
Do we have a panel design? If not, I’ll handle...

**Comment by lidel** [comment]
Not really, however we have a similar expandable thingy (`>`)  on _Settings_ screen:

> ![Screenshot_2019-10-15 Settings - IPFS](https://user-images.githubusercontent.com/157609/66853010-9c608600-ef7e-11e9-8008-176bd71643bb.png)


when clicked it expands inline:

> ![Screenshot_2019-10-15 Settings - IPFS(1)](https://user-images.githubusercontent.com/157609/66853021-a1bdd080-ef7e-11e9-8b5f-148da8ff3099.png)

not sure if this is the best way, but we probably should have consitent design in both places (or change `>` to something else)

**Comment by hsn10** [comment]
I dont think this is a bug. It maybe confusing and need some UI adjust but behavior is correct.

**Comment by SgtPooki** [comment]
I personally like the B approach but would prefer a pattern of tooltip over numbers for more information.

@juliaxbow what do you think?

**Comment by SgtPooki** [comment]
We will move forward with the C approach previously discussed: 
![image](https://github.com/ipfs/ipfs-webui/assets/1173416/ad0316ab-0f12-49b7-9184-dc39c90af3b3)
