### ISSUE TITLE
Move to IPFS org?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/ipfs-webui#1392]
This module is bundled with IPFS, we get issues opened about it on other repos, it's a useful tool and a key part of the app.

We should move it to the main IPFS org.

**Comment by achingbrain** [comment]
@lidel @hacdias any thoughts?

**Comment by lidel** [comment]
I don't have any strong feelings either way, but in the past we moved GUI projects to `ipfs-shipyard` as they were not "part of actual protocol". 

Perhaps this is a good oportunity to create a policy for which projects belong where?
How ipfs-webui is different from ipfs-desktop and ipfs-companion?
Is being bundled with go-ipfs and js-ipfs the only factor?

**Comment by hacdias** [comment]
I agree with @lidel on creating a policy about what belongs where. And I also remember moving everything here because it wasn't (and isn't) part of the actual protocol.

**Comment by lidel** [comment]
We moved ipfs-webui (and desktop, companion) to ipfs.
