### ISSUE TITLE
Unpinning one item initiates a full refresh of the pin-list

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-webui#1404]
**Describe the bug**
When one item of the list of pins is unpinned, the UI initiates a full refresh of the pin-page, which takes a lot of time.

**Expected behavior**
The UI understands that unpinning one item from the "root" of pins will just remove the item from the list, and hide it, and work with the delta data until the next refresh is initiated.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Version 79

**Additional context**
Probably related to https://github.com/ipfs-shipyard/ipfs-webui/issues/1403

**Comment by lidel** [comment]
The list of low level pins will be removed from GUI as part of https://github.com/ipfs/ipfs-gui/issues/91
