### ISSUE TITLE
Pinning integration: Make Files screen functional

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-webui#1502]
_Note: This issue is part of a larger [pinning service integration epic](https://github.com/ipfs/ipfs-gui/issues/91) undertaken spring/summer 2020._

### In brief
Make the UI elements for the Files screen that were stubbed out in #1500 functional by integrating with the to-be-built IPFS Pinning API.

**⚠️ IMPORTANT:** Work on this issue is blocked by issues #1500 and #1504 in addition to completion of the API itself.

**Comment by lidel** [comment]
Closed as part of https://github.com/ipfs/ipfs-gui/issues/91
