### ISSUE TITLE
Pinning integration: Make Settings screen functional

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-webui#1503]
_Note: This issue is part of a larger [pinning service integration epic](https://github.com/ipfs/ipfs-gui/issues/91) undertaken spring/summer 2020._

### In brief
Make the UI elements for the Settings screen that were stubbed out in #1501 functional by integrating with the to-be-built IPFS Pinning API.

**⚠️ IMPORTANT:** Work on this issue is blocked by issue #1501 in addition to completion of the API itself.

**Comment by lidel** [comment]
Closed as part of https://github.com/ipfs/ipfs-gui/issues/91
