### ISSUE TITLE
'Delete' modal: improve pin guidance and overall language 

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1634]
> I was about to fill this as separate issues, but I feel it's better to think about final UX that tries to address it all.
> @ipfs-shipyard/gui 

### Situation

Right now user can pin an item via Files screen, and then use the same GUI to remove it:

> ![Screenshot_2020-09-15  Files IPFS](https://user-images.githubusercontent.com/157609/93265570-13168c80-f7a9-11ea-9436-a9360a0a4196.png)

### Problem

If deleted item was pinned, the low level pin remains, silently protecting the CID  from being garbage-collected.

This disconnect between low level pins and MFS will become a problem when we implement https://github.com/ipfs-shipyard/ipfs-companion/issues/888#issuecomment-689666068 as part of https://github.com/ipfs/ipfs-gui/issues/91. Pinning via IPFS Companion would create local pin AND add file to MFS.

Perhaps we should adjust the default behavior and remove local pin when a pinned resource is removed from MFS via GUI in Files screen?

### Solution ideas

GUI users should not need to know what low level pins are, Files screen should be enough on its own for managing "pinned" data.
If they remove something from "Files", they expect it to not be kept around forever. There should be a way to keep the pin if a power user knows what they are doing, but it should not be the default behavior. Otherwise user repos will grow and they will end up with thousands of dead pins.

What if we extend the Delete dialog and display some additional UI if Deleted file is pinned?

Some ideas:

- checkbox 
  - `[x] Remove local pin` or.. `[ ] Keep local pin`
  - Q: should there be an option to remove remote pins too?
- button
  - `Delete and unpin` (make it default)  and then regular `Delete` that keeps the pin is grayed out

No strong feeling here, but checkbox may be a better pattern if we want to provide other options, such as  "remove blocks from local repo" (see below)

## Clear description of what "Delete" really means

aka MFS removal vs garbage collection vs removal working only on local node

### Situation

- If something is in MFS  it is implicitly pinned  (protected from GC).
- If user removes something from MFS, even if it is not explicitly pinned, it is still in the repo until GC, and user will see the disk space used did not change
- Even if content is GC'd, or every block is manually removed via `ipfs block rm`, the change is local, and the data may be safe and sound on a different node.

### Problem

Due to this, "Delete" may not be the best description for the operation of "removing a pointer to a CID from MFS".

### Solution ideas

- give user an option to truly remove blocks from local repo: `[ ] purge data blocks from local cache` 
- rename? be more honest about operation being more a `Forget`/`Discard` than "Delete"

----

Apologies for a long brain dump, but wanted to have all concerns around Delete modal in one place, so we can figure out how to improve it in premaration for pinning services integration.

Feedback/ideas will be really appreciated!

**Comment by rafaelramalho19** [comment]
I would go with `Unpin and Delete` (order makes more sense I guess?), it gives the subtle message to the user that the file should be unpinned first if he really wants to fully delete it :)

**Comment by jessicaschilling** [comment]
For your consideration/debate ...

![image](https://user-images.githubusercontent.com/1507828/93384047-c4590900-f821-11ea-92cc-8f054a23c846.png)

**Comment by lidel** [comment]
@jessicaschilling YES PLEASE :+1: 

To avoid questions "Why my repo size did not change when I removed this 2GB video" we could also add a third checkbox (unchecked by default) saying `Run garbage collection in the background`  or `Proactively purge all unused blocks from the local cache`

It will be easy to wire up – all  we need to do is to asynchronously run [`ipfs.repo.gc({quiet: true})`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/REPO.md#ipfsrepogcoptions) in the background.

**Comment by jessicaschilling** [comment]
Sounds good, but can introduce as-is first? A little concerned about cognitive overload for three check boxes when the third does something the user can do in the menu today.

**Comment by ericronne** [comment]
@jessicaschilling that modal strikes me as crystal 🔮 clear. 
Nice 👌 

My only suggestions are visual tweaks to the component: to make the text darker (to add gravitas), consider left-aligning it (for readability), and possibly use a lighter font weight for the checkbox items.

**Comment by jessicaschilling** [comment]
@ericronne All good points - we've actually got a lack of consistency across modals (this is an existing one but just new text), so probably best fodder for its own issue.

**Comment by rafaelramalho19** [comment]
> @jessicaschilling YES PLEASE 👍
> 
> To avoid questions "Why my repo size did not change when I removed this 2GB video" we could also add a third checkbox (unchecked by default) saying `Run garbage collection in the background` or `Proactively purge all unused blocks from the local cache` or ... something more human 🤖
> 
> It will be easy to wire up – all we need to do is to asynchronously run [`ipfs.repo.gc({quiet: true})`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/REPO.md#ipfsrepogcoptions) in the background.

@lidel are we okay with keeping that a webui/desktop only feature, or should we request this functionality in go-ipfs?

**Comment by jessicaschilling** [comment]
@ericronne FYI, opened https://github.com/ipfs-shipyard/ipfs-webui/issues/1643 for modal standardization, but want to wait until a few other items get merged in order to avoid conflicts. Just wanted to confirm that it's on the radar.

**Comment by jessicaschilling** [comment]
This is ready for wiring up in https://github.com/ipfs-shipyard/ipfs-webui/pull/1644.

**Comment by lidel** [comment]
> @lidel are we okay with keeping that a webui/desktop only feature, or should we request this functionality in go-ipfs?

@rafaelramalho19 The way I see it, CLI users can already trigger gc by executing `ipfs repo gc` after they remove things, so nothing is missing in go-ipfs. What we would do here is to give the same capability to GUI users :)
