### ISSUE TITLE
Renaming file will override existing one without warning

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs/ipfs-webui#1667]
**Describe the bug**
When you `rename` a file to match a file that already exists with that name, it overrides the later without any warning.

**To Reproduce**
1. Go to files page
2. Have 2 files: `1.png` and `2.png`
3. Rename `2.png` to `1.png`
4. No warning that original `1.png` will be permanently lost with the rename

**Expected behavior**
@jessicaschilling thoughts on the expected behavior? Maybe open a modal that requires confirmation before actually replacing file?

**Comment by jessicaschilling** [comment]
@rafaelramalho19 Modal to confirm overwrite would be totally consistent; good call. I'll mock something up in the next day or so if that's OK for you 😊

**Comment by jessicaschilling** [comment]
Related is https://github.com/ipfs-shipyard/ipfs-webui/issues/1612 for overwrite on file drag -- we can probably use the same modal in both places.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 -- how about this?
![image](https://user-images.githubusercontent.com/1507828/95379860-2c3fc400-08a3-11eb-9a9f-f233fa82bb09.png)
- Icon is `stroke_attention`
- Headline is `Overwrite file?`
- Text is `You already have a file named (funny-cat.gif) in this directory. Are you sure you want to overwrite it? This action is permanent and cannot be reversed.`
- Buttons are `Overwrite` and `Cancel`

**Comment by jessicaschilling** [comment]
NB: Latest mockup of this is at https://github.com/ipfs-shipyard/ipfs-webui/issues/1612#issuecomment-709605768 for feedback.

**Comment by SgtPooki** [comment]
closing in favor of https://github.com/ipfs/ipfs-webui/issues/1612
