### ISSUE TITLE
Handling a case when file with a matching name is imported

### ISSUE THREAD

**Issue by Gozala** [ipfs/ipfs-webui#1669]
**Describe the bug**

At the moment attempt importing a file into a directory that contains file with a same name will eventually throw an exception when imported file is copied to the destination & crash the program (as reported by @rafaelramalho19)

https://github.com/ipfs-shipyard/ipfs-webui/pull/1655/files

**Expected behavior**

We should figure out a way to handle name collisions, rather than swallowing an error or logging it into a console. 

1. We could check for name collisions prior we even start import. 
2. We could deal with name collisions as they occur, similar to how OSs do e.g. suffix with a number. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21236/95632485-963ea180-0a3a-11eb-9e97-4a5ca8cab124.png)

**Comment by jessicaschilling** [comment]
Additional thought: rather than increment numbers, perhaps use something like the last 4(?) characters of the file's hash.

**Comment by jessicaschilling** [comment]
Related file overwrite issues (cc @rafaelramalho19):
- https://github.com/ipfs-shipyard/ipfs-webui/issues/1612
- https://github.com/ipfs-shipyard/ipfs-webui/issues/1667

**Comment by lidel** [comment]
Closing in favor of https://github.com/ipfs/ipfs-webui/issues/1612 which includes mentioned mockups and further discussion.
