### ISSUE TITLE
Files: show CumulativeSize for directories

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1687]
Right now (v2.11.4) ipfs-webui reads `Size` value from `ipfs.files.stat('/path/in/mfs')`.
Unfortunately, the `Size` of a directory is `0`, which results in missing size for dirs:

> ![2020-11-06--23-16-29](https://user-images.githubusercontent.com/157609/98419810-20077c00-2086-11eb-8dd6-88222e5399aa.png)

I believe in this case makes more sense to  show total size of directory, including the metadata.
So the fix is to detect `Type` being `directory` and use `CumulativeSize` instead. 

cc @rafaelramalho19  mind prioritizing this? should be easy win :pray:

**Comment by rafaelramalho19** [comment]
I tried multiple ways to debug this, but it appears that in the codebase this is already handled: 
![image](https://user-images.githubusercontent.com/24696635/103575077-fec9dd00-4ec8-11eb-9393-c2c88e1a33e2.png)


Are you sure you're using the latest main branch version?

**Comment by lidel** [comment]
Hm... indeed! It took me a while to reproduce it. Turns out sizes are missing only if... your directory has more than 100 items :trollface: 

https://github.com/ipfs-shipyard/ipfs-webui/blob/9ccb2e5d7b27416369eb5c63a27463af49242ab2/src/bundles/files/actions.js#L579

I suspect this limit was introduced a long time ago as a fail-safe when listing huge directories.

While we should have a limit, its too low atm. Perhaps:
- short term: open a PR that bumps the number to 1000 
- long term: refactor to execute `files.stat` for the first 1000k items, and then fetch sizes on-demand when user scrolls past that point.

@rafaelramalho19 I'm ok with closing this by bumping limit to 1k.
Making it smarter could be a time sink, so the long term fix could be part of redoing Files UI, 
which  afaik  @jessicaschilling plans to do that at some point anyway.
