### ISSUE TITLE
Files: import drawer opens without a reason

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1704]
**Describe the bug**

For some reason an empty import drawer _sometimes_ appears when I switch between screens or click on menu:

> ![2021-01-05--14-55-27](https://user-images.githubusercontent.com/157609/103654473-320e7980-4f66-11eb-8b8d-f6e43ebf5b7a.png)

**To Reproduce**
1. Go to 'Files'
1. Go to 'Settings' (or 'Explore')
1. Go back to 'Files'
1. See the drawer  already open (or go to next step)
1. Click on three dot menu '...' next to a directory
1. See the drawer pop up

**Expected behavior**

The drawer should not be displayed when "0 items"

**Versions:**
 - Browser: Firefox and Brave
 - WebUI:
    - :broken_heart:  `master` branch @ 9ccb2e5d7b27416369eb5c63a27463af49242ab2
    -  :green_heart: v2.11.4 does not have this bug

@rafaelramalho19  are you able to reproduce? perhaps something changed around  #1685?

**Comment by jessicaschilling** [comment]
FWIW, I've not seen this in `master` yet but will keep an eye out.

**Comment by rafaelramalho19** [comment]
Not able to reproduce, tried 100x times and still didn't manage to see this happen 🤔

**Comment by jessicaschilling** [comment]
I'm going to move this out of the "new issues" column but let's all keep an eye out for recurrences.

**Comment by lidel** [comment]
Seems that it got fixed during recent refactors, I no longer experience it :man_shrugging:
