### ISSUE TITLE
Change default gateway for shareable links?

### ISSUE THREAD

**Issue by amackenzie** [ipfs/ipfs-webui#1717]
**Is your feature request related to a problem? Please describe.**
Currently, the shareable links default to using ipfs.io to resolve the content. It would be nice if we were able to set which gateway we'd like to use (whether another public gateway or our own).

**Describe the solution you'd like**
Ideally, there's a box somewhere I can enter a gateway URL to be used whenever I copy from a shareable link.

**Comment by SgtPooki** [comment]
This is possible via the settings screen: 



![Image](https://user-images.githubusercontent.com/1173416/205743263-c114e720-bc42-4e1e-859b-790d8451faee.png)



Closing
