### ISSUE TITLE
IPLD Explorer error: Invalid version, must be a number equal to 1 or 0

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1726]
Opening IPLD Explorer → Project Apollo on a fresh browser profile (empty caches) produces:

> ![2021-02-26--15-10-39](https://user-images.githubusercontent.com/157609/109310521-f052ce80-7844-11eb-97f1-0a984b1b3de9.png)

Was able to reproduce in Firefox and Brave.

Needs analysis, I suspect CID lib versions got out of sync between webui and explorer component.

**Comment by woss** [comment]
TBH the webui source code is quite confusing to read and understand. Probably it has been written by a pure genius. :) 

Issue is that the `cid.version` is required to be `0` or `1`, but it gets the `Uint8Array` and then it fails here https://github.com/multiformats/js-cid/blob/master/src/cid-util.js#L19 and it starts from here https://github.com/ipld/js-ipld-dag-pb/blob/master/src/dag-link/dagLink.js#L25

There is a lot going on here, I spent 3 hours debugging and I found nothing.  I know my way around programming and JS but this amount of complexity is just not needed. 

Little advice to the core team, if you want people to help you, make sure they can debug and understand the code.
