### ISSUE TITLE
IPFS Desktop v0.8.0

### ISSUE THREAD

**Issue by NFT-KING** [ipfs/ipfs-webui#1728]
Why is it that when I add an image to IPFS sometimes it takes a while to show up on the https://ipfs.infura.io/ipfs gate way?  Do I need to adjust any settings?

**Comment by SgtPooki** [comment]
@NFT-KING The size of your image, your closest peers, and many other factors all play a part in this delay. You may want to check discuss.ipfs.tech for general support or prior conversations regarding any network latency, but you can also check out pl-diagnose: https://pl-diagnose.on.fleek.co or other tools: https://pl-diagnose.on.fleek.co/#/toolbox?backend=https%3A%2F%2Fpl-diagnose.onrender.com
