### ISSUE TITLE
Could not connect to the IPFS API

### ISSUE THREAD

**Issue by franjavi01** [ipfs/ipfs-webui#1729]
I cannot connect in the IPFS desktop application

In the attached document is the screenshot of the panel

![IPFS](https://user-images.githubusercontent.com/36012280/111073981-56944e00-84e1-11eb-976b-02bbdbbb57f0.jpg)

**Comment by franjavi01** [comment]
155 / 5000
Resultados de traducción
Please Is there any solution workaround? I have not been able to access the
IPFS desktop application for 3 days. I attach the screenshot again

**Comment by MagnusBee** [comment]
![5b80bc0557dff09543e76b9027b7a88c](https://user-images.githubusercontent.com/64299420/111963713-bc896280-8aeb-11eb-9de3-2fd326deb045.png)

**Comment by lidel** [comment]
@franjavi01 did update to the latest ipfs-desktop (https://github.com/ipfs/ipfs-desktop/releases/latest) solve your issue?
@MagnusBee what do you mean by "lift the node"?

**Comment by franjavi01** [comment]
I uninstalled it and I reinstalled it.  now it works

Thank you
