### ISSUE TITLE
Re-add JS-IPFS testing on CI

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs/ipfs-webui#1730]
Since js-ipfs doesn't support remote pinning services for the time being, we need to wait for the implementation.

After js-ipfs supports remote pinning:
- Revert https://github.com/ipfs-shipyard/ipfs-webui/commit/d20e4e30ae53d412ad1ec43401d34936e2a86e9d

Relevant PR: https://github.com/ipfs-shipyard/ipfs-webui/pull/1713

**Comment by lidel** [comment]
We need to fix https://github.com/ipfs/ipfs-webui/issues/1737 first, then we should re-add JS tests on CI to run by default.

**Comment by SgtPooki** [comment]
wontfix, we're decoupling from js-ipfs
