### ISSUE TITLE
Imports to directories with spaces fails

### ISSUE THREAD

**Issue by justicenode** [ipfs/ipfs-webui#1733]
**Describe the bug**
File uploads to a mfs folder that has a space in its name will always fail

**To Reproduce**
1. Create a folder with a space in the name
2. try to upload a file to it

**Expected behavior**
the file showing up after a few seconds and the upload to not instantly fail

**Screenshots**

https://user-images.githubusercontent.com/26402137/111774008-29fc7f80-88af-11eb-97f6-5bed6e1f2e13.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909
 - Browser: Firefox developer edition v87.0b3 (64-Bit)
 - Version: UI v2.11.4 | Revision 69cd414

**Additional context**
The problem is with the request being uri encoded before getting sent to the go-ipfs daemon. If you have developer tools open and edit & resend the request replacing the %20 with a space it works fine.

**Comment by justicenode** [comment]
bump @lidel

If theres any additional info I can provide let me know. I dont think I can solve this issue myself as I dont really know the codebase but I might have a look.

**Comment by lidel** [comment]
Thank you @justicenode – very good bug report, the problem was limited to drag&drop.
This should be fixed in the next release: https://github.com/ipfs/ipfs-webui/pull/1764
