### ISSUE TITLE
desktop find file bug

### ISSUE THREAD

**Issue by DaBaiTuuu** [ipfs/ipfs-webui#1739]
**Describe the bug**
when i search a wrong hash in desktop then behave the file-window stucks. 

**To Reproduce**
1.give a wrong hash，which means the file didnt exist
2.click browse
3 it's always show a finding flash
![image](https://user-images.githubusercontent.com/58634162/112733330-bc4ff380-8f3f-11eb-90d7-bfb7c7ae526b.png)

**Expected behavior**
even show file didn't exist

**Screenshots**

![image](https://user-images.githubusercontent.com/58634162/112733438-557f0a00-8f40-11eb-85ba-abea9bcdbaf2.png)

**Desktop (please complete the following information):**
 - windows pc
 - Browser [chrome]
 - Version [69cd414]

**Comment by DaBaiTuuu** [comment]
UI v2.11.4

**Comment by lidel** [comment]
I confirmed this with v2.12 and `QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMns` (changes last character from `R` to `s` making it "invalid"). The state is:

> ![2021-05-28--15-53-56](https://user-images.githubusercontent.com/157609/119994686-1e26eb00-bfcd-11eb-94af-cc7d121ab7f6.png)


Let's continue in https://github.com/ipfs/ipfs-webui/issues/1794 as it is the same use case.
