### ISSUE TITLE
Files: Import from IPFS does not refresh file list

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1740]
![2021-03-30--00-38-49](https://user-images.githubusercontent.com/157609/112908784-74bc9980-90f0-11eb-8ab2-6b6a57cd869c.png)

Importing via above menu action does not show newly added resource on the file list, I had to manually refresh page.
Sounds like an easy fix, we should trigger refresh dir listing after `files cp`

**Comment by jessicaschilling** [comment]
Also ref: https://github.com/ipfs/ipfs-webui/issues/996
I believe there was a similar issue elsewhere from early this year, but can't seem to find it.
