### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by 547176052** [ipfs/ipfs-webui#1745]
![image](https://user-images.githubusercontent.com/26636842/113123527-41405300-9247-11eb-8481-4426a5f76a1b.png)

**Comment by lidel** [comment]
@547176052 a lot of Files screen was refactored in  the latest release, please update to [the latest ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop/releases/latest) and reopen if the problem is still present there.
