### ISSUE TITLE
Miss Translation Text

### ISSUE THREAD

**Issue by akimoto72738** [ipfs/ipfs-webui#1765]
**Hi,teams,**

**I'm glad to see the latest version, but I found some problems that the translated text is not displayed, and I'm not sure if it's my own problem**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/67720156/115408720-afaf7a00-a223-11eb-82eb-cb7faf658444.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/67720156/115414407-96f59300-a228-11eb-847b-ec71849b647f.png">

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/67720156/115409720-96f39400-a224-11eb-8c8a-a107310838df.png">

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/67720156/115411616-32393900-a226-11eb-9e95-41d252203a2b.png">

**I'm very clear that I have translated all the texts in transifex**

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/67720156/115409059-fbfaba00-a223-11eb-8869-41561515714a.png">

**Comment by akimoto72738** [comment]
hi guys

Now most of the translated texts are displayed normally, but there are still some untranslated texts
![image](https://user-images.githubusercontent.com/67720156/115998383-8757bf00-a619-11eb-863d-400a5e0db483.png)

**Comment by lidel** [comment]
@akimoto72738 thank you for reporting this.

This sounds a lot like issue @olizilla experienced:

> <img width="998" alt="Screenshot 2021-04-23 at 14 26 26" src="https://user-images.githubusercontent.com/157609/116166890-489c3480-a6ff-11eb-9041-b71b90be9bac.png">
> <img width="520" alt="Screenshot 2021-04-23 at 14 36 55" src="https://user-images.githubusercontent.com/157609/116166891-4934cb00-a6ff-11eb-84c2-8c1b9463d4ef.png">
> <img width="362" alt="Screenshot 2021-04-23 at 14 38 22" src="https://user-images.githubusercontent.com/157609/116166894-4934cb00-a6ff-11eb-90b7-368a601b4bce.png">

I was not able to reproduce, but I think a plausible explanation is that if you used older version and had locale data cached, newly added keys would not be present in the cache and thats why you get key names as placeholders.

After a few days, the cache expired (iirc its set to 7 days) and you got correct strings. 
I filled https://github.com/ipfs/ipfs-webui/pull/1769 to scope i18n cache per webui version, similar to what we do with ipfs-geoip already.

@olizilla I am not sure how the above could happen in the Desktop, so it could be something else. 
Any ideas or steps how to reproduce the bug reliably?

**Comment by olizilla** [comment]
Yes, I suspect I'm seeing a "missing english fallback" too... my locale is `en-GB`, and I see in the network tab a bunch of failed requests for translation bundles for that locale

```
GET webui://-/locales/en-GB/app.json net::ERR_FILE_NOT_FOUND
GET webui://-/locales/en-GB/welcome.json net::ERR_FILE_NOT_FOUND
...
```
