### ISSUE TITLE
The private network browsing file references the ipfs.io gateway

### ISSUE THREAD

**Issue by zemelLeong** [ipfs/ipfs-webui#1767]
**Describe the bug**
The private network browsing local cluster file references the `ipfs.io` gateway.
![image](https://user-images.githubusercontent.com/26835087/115504359-66eed400-a2aa-11eb-975c-ccfe67df5eba.png)

**Comment by lidel** [comment]
Fix here is to provide two links: "open on ipfs.io" + "open on local gateway"

**Comment by lidel** [comment]
This may be caused by https://github.com/ipfs/go-ipfs/issues/8230 – webui uses that CID for testing if local gateway is available.
