### ISSUE TITLE
Pinning problems when a service name includes dot

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1770]
## Problem in GUI

Found in v0.12.1 while testing https://nft.storage  – having "." in name means bad time in both GUI and CLI.

> ![2021-04-27--23-45-04](https://user-images.githubusercontent.com/157609/116316756-b05f8780-a7b2-11eb-9119-5cc398312edd.png)

Quick fix for GUI is to replace "." with "-" or "_" when Service is added  from GUI, but  that won't solve the problem if  one added it via CLI:

## Problem in CLI

```console
$ ipfs pin remote service add nft.storage https://nft.storage/api [secret]
$ ipfs config Pinning.RemoteServices.nft.storage.Policies.MFS.Enable
Error: failed to get config value: "Pinning.RemoteServices key has no attributes"
```

## How to fix this?

@alanshaw @aschmahmann given that we use "nft.storage" in `pin remote`  examples on https://nft.storage, we should address this before the problem escalates when people start using it :sweat_smile: 

I tried explicit percent encoding `%2E` but it does not work  (we would have to modify both webui and go-ipfs to allow that). 

Is there a preexisting way to pass `.` correctly?

If not, we need to either
- (a)  tweak go-ipfs to percent-decode service name to make `%2E` work,
- (b) ban `.` from service names and replace with `-` in docs
- (c) ?? (is there other way to resolve this?)

**Comment by alanshaw** [comment]
Does this work?
```
$ ipfs config Pinning.RemoteServices["nft.storage"].Policies.MFS.Enable
```

**Comment by lidel** [comment]
Sadly no:
```console
$ ipfs config Pinning.RemoteServices["nft.storage"].Policies.MFS.Enable
Error: failed to get config value: "Pinning key has no attributes"
```

**Comment by aschmahmann** [comment]
@lidel is this specific to pinning services or can `ipfs config` not properly deal with things like modifying public gateway properties (e.g. https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#gatewaypublicgateways)?

**Comment by lidel** [comment]
@aschmahmann  yes, it is a global problem, we seem to lack `ipfs config --json` notation that removes the ambiguity of `.`
