### ISSUE TITLE
Let IPFS have the same function as the server, and can realize the operation of the network program server.

### ISSUE THREAD

**Issue by qwe231cvb** [ipfs/ipfs-webui#1771]
At present, IPFS can only store static files, but it cannot provide services for the operation of network programs and the interaction of data like a server. Only static files can be stored, which makes the application fields of IPFS very limited.
I hope it can have the same functions as the linux or unix server, so that the server of the network program can be deployed on IPFS, so that all network programs can be decentralized.
What are the decentralized applications? Perhaps people would say that it is a Dapp. Although Dapp can realize the interaction between smart contracts and the blockchain and has certain decentralized properties, this is only reflected in the encryption and decentralized properties of account asset transactions, but for Other operations of Dapp still need to run on servers such as unix or linux. In this way, the operation of the server of the network program and the data interaction with the client can be ensured. So strictly speaking, Dapp is not completely a decentralized application, because it depends on a centralized server.
This is exactly the problem that IPFS needs to solve. Let IPFS replace a centralized server, so that Dapp can be completely decentralized. It can also decentralize network programs and websites. This should be the direction of IPFS improvement. If it can be realized, this will be a huge change in the Internet field.

**Comment by qwe231cvb** [comment]
Did the maintainer see my post?

**Comment by lidel** [comment]
@qwe231cvb yes :-) And I agree with @welcome that you should re-post this in https://discuss.ipfs.io/c/ecosystem/15
We use github for bugs/well-defined issues, and this belongs to forums.
