### ISSUE TITLE
Incorrect use of ‘filesize’

### ISSUE THREAD

**Issue by JohnGao818** [ipfs/ipfs-webui#1778]
**Describe the bug**
According to the latest standard definition: 
1024 B = 1 KiB; 1024 KiB = 1MiB; 1024 MiB = 1 GiB。
1000 B = 1 KB; 1000 KB = 1MB; 1000 MB = 1 GB。
So the correct usage of the function filesize is:
fileSize(1024, {standard: 'iec'}); // 1 KiB;
fileSize(1000, {base: 10}); // 1KB;
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50511900/117613957-36f46b80-b19a-11eb-8106-27629be43d05.png)
![image](https://user-images.githubusercontent.com/50511900/117595934-ae170900-b174-11eb-8e23-0f4419edf51f.png)
Correct result should be：
336 MiB( base 2) or 352.66 MB(base 10)；
The follow screenshots can provide proof；
![image](https://user-images.githubusercontent.com/50511900/117614035-525f7680-b19a-11eb-9f89-0c387f94dce9.png)
![image](https://user-images.githubusercontent.com/50511900/117596238-7eb4cc00-b175-11eb-90af-5807a2ddd401.png)

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Browser chrome
 - Version 90.0.4430.93

**Smartphone (please complete the following information):**

**Additional context**
SI, or International System of Units: http://en.wikipedia.org/wiki/SI_prefixes#List_of_SI_prefixes
Usage of filesize: https://github.com/avoidwork/filesize.js

**Comment by JohnGao818** [comment]
Can someone help me with this problem

**Comment by lidel** [comment]
@JohnGao818 would you be interested in submitting a PR with a fix?
I believe the fix is to add `{standard: "iec"}`  in every place where we use filesize.

**Comment by lidel** [comment]
@JohnGao818  please take a look if screenshots in #1791 look good to you.
