### ISSUE TITLE
Wrong encoding on peer location name (ý)

### ISSUE THREAD

**Issue by danisztls** [ipfs/ipfs-webui#1787]
**Describe the bug**
On the peers section special characters like `ã` and `é` in city names are being displayed as `ý`.

**To Reproduce**
Open peers section when connected to peers in cities such as Montréal and São Paulo.

**Expected behavior**
City names being displayed correctly.

**Desktop:**
 - OS: Arch Linux
 - Browser: Chromium
- UI v2.11.4 Rev 69cd414

**Screenshots:*
![Screenshot from 2021-05-17 09-56-06](https://user-images.githubusercontent.com/13279154/118492196-2c842580-b6f6-11eb-87ca-1b4eb3d947d0.png)

**Comment by lidel** [comment]
I believe this is fixed in v2.12 since we merged geoip update from  (2020-10-13) (#1675)
Please reopen if you see any new encoding issues with the latest version.
