### ISSUE TITLE
Traffic Graph always shows outgoing abve incoming, even when it is lower

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/ipfs-webui#1797]
**Describe the bug**
The outgoing line is always higher than incoming

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://webui.ipfs.io.ipns.localhost:8080/#/
2. Scroll to the traffic graph
3. Wait for incoming to be higher than outgoing

**Expected behaviour**
If the outgoing is lower, the line should go down below incoming

**Screenshots**
<img width="956" alt="Screen Shot 2021-05-29 at 11 38 48" src="https://user-images.githubusercontent.com/58151048/120076221-7663f880-c072-11eb-82ac-985accd50358.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser Firefox
 - Version 90.0a1 (2021-05-29)

**Additional context**

**Comment by unbeatable-101** [comment]
<img width="956" alt="Screen Shot 2021-05-29 at 11 38 48" src="https://user-images.githubusercontent.com/58151048/120076276-c5aa2900-c072-11eb-88a0-43eebf3d022e.png">
Very bad mockup of what I imagine it should look like

**Comment by lidel** [comment]
The graph is "stacked".  The height represent total in+out, _there is no overlap_.

TODO: come up with more intuitive way of drawing this graph,  some ideas:

- easy "fix": put outgoing below incoming, making it less "scary"
- make them overlap, but add transparency  
- move incoming to the top (graphana-style)
