### ISSUE TITLE
Pins don't make sense in latest files ui

### ISSUE THREAD

**Issue by kallisti5** [ipfs/ipfs-webui#1808]
**Describe the bug**
The pins in the webui are pretty non-nonsensical.  

By adding files to MFS, doesn't the local node automatically pin all data?  Opening folders shows "pinned" data doesn't have a recursive pin.

Maybe the webui isn't identifying recursive pins properly?

**Screenshots**
"haiku" not pinned + "haikuports" pinned here:
![pin_status](https://user-images.githubusercontent.com/100110/123109843-325ddc80-d401-11eb-8759-00c6920f7010.png)

Nothing within "haikuports" pinned here:
![pin_b](https://user-images.githubusercontent.com/100110/123112333-3d197100-d403-11eb-930c-e8258feec692.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Opera

**Additional context**
UI v2.12.3

**Comment by lidel** [comment]
Correct: only direct pins are shown, and indirect pins have no indicator at the moment.

I'm closing this, as we already track adding indicator for indirect pins in https://github.com/ipfs/ipfs-webui/issues/1736
If you have any suggestions what way of indicating indirect pins feels intuitive, please comment on the linked issue :pray:
