### ISSUE TITLE
Plain text file without extension acts as an "image" and is not select-able

### ISSUE THREAD

**Issue by kallisti5** [ipfs/ipfs-webui#1809]
**Describe the bug**
Basic text is rendering as an "image" and isn't select-able.

**Expected behavior**
Being able to copy + inspect text data.

**Screenshots**

These are all "images" and cannot be selected as text:

![image](https://user-images.githubusercontent.com/100110/123113144-ed877500-d403-11eb-84d7-b8179d710c02.png)
![text_image](https://user-images.githubusercontent.com/100110/123113510-39d2b500-d404-11eb-8fe7-1a1aab2ca03f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Opera, Firefox

**Additional context**

Version: UI v2.12.3

**Comment by kallisti5** [comment]
This MFS data can be seen here: https://de.hpkg.haiku-os.org/haikuports/master/x86_64/current

**Comment by lidel** [comment]
Indeed there seem to be a bug when `.txt` extension is not specified but the file is mime-sniffed as plain text:
- https://webui.ipfs.io/#/ipfs/QmVvhiTJQbSnK5R1xeamhyoE4eUnPoqZfSyajHJi2bniqp/repo_consistency.txt → selection and copying works fine
- https://webui.ipfs.io/#/ipfs/QmVvhiTJQbSnK5R1xeamhyoE4eUnPoqZfSyajHJi2bniqp/repo.sha256 → selection is disabled   
  - the entire thing becomes draggable, which suggests that some logic falls back to the same lane as images
