### ISSUE TITLE
希望能够添加一个提供显示下载的实际界面

### ISSUE THREAD

**Issue by innocentshen** [ipfs/ipfs-webui#1813]
当我想把已经上传的文件重新下载至本机时，当我点击下载按钮时，我并不能知道我是否正常下载该文件，也不能得知下载的具体进度，因此我想，团队能否添加一个新的界面以用以显示是否在成功下载，具体的下载进度等。谢谢！

**Comment by FledgeXu** [comment]
1. 请用英文发issue
2. 你可以用内置的网关（Gateway）下载内容，这样就有你需要的东西了。

**Comment by innocentshen** [comment]
I get it,thank!

FledgeShiu ***@***.***> 于2021年7月2日周五 下午12:37写道：

**Comment by lidel** [comment]
LEt's continue in https://github.com/ipfs/ipfs-webui/issues/1814
