### ISSUE TITLE
Feature: Add `Open in Gateway`

### ISSUE THREAD

**Issue by FledgeXu** [ipfs/ipfs-webui#1814]
**Is your feature request related to a problem? Please describe.**
In #1813, the user wants a feature which is showing the downloading progress in the WebUI. However, If users can download through the browser, they can get the download progress they want. So if we can add a new Button called `Open in Gateway` or`Open in Browser`, it will be convenient.

**Describe the solution you'd like**
Before:
![image](https://user-images.githubusercontent.com/16664654/124249506-892c8a00-db56-11eb-8604-6a4945407285.png)
After:
![image](https://user-images.githubusercontent.com/16664654/124249428-7619ba00-db56-11eb-8ce7-114a22fd8b38.png)

**Describe alternatives you've considered**
Or Add a Button to help users copy the gateway URL of a file.

**Additional context**
We can use `ipfs config Addresses.Gateway` to get Gateway address.

**Comment by lidel** [comment]
Notes from triage:
- right now the Download button uses JS API and a `blob:`  as a source 
- fix here is to switch to HTTP link at a local gateway
  -  single file would have `/ipfs/{cid}?filename=foo&download=true` to ensure proper `content-disposition
  - a directory – tbd, either `/api/v0/` or `?format=tar` (whichever is available when this is tackled)

**Comment by FledgeXu** [comment]
I agree with changing the Download button instead of adding a new action.
About directory downloading,`?format=tar` needs ipfs/go-ipfs#8234. However, Windows doesn't support tar unarchive. Maybe using zip is a better choice?

**Comment by lidel** [comment]
Support for tar has been included in Microsoft Windows since Windows 10:
https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

**Comment by FledgeXu** [comment]
@lidel Yes, I just tested it. Windows still doesn't support the `*.tar` in GUI.
![image](https://user-images.githubusercontent.com/16664654/127730626-2038bc83-0089-46bf-bef2-05dca34fbb62.png)

**Comment by SgtPooki** [comment]
I believe this should be fixed with https://github.com/ipfs/ipfs-webui/pull/1894. Please let us know if you continue to have issues.
