### ISSUE TITLE
Fail when trying to run webui with ipfsd-ctrl

### ISSUE THREAD

**Issue by denyncrawford** [ipfs/ipfs-webui#1817]
**Describe the bug**
I can't connect the webui with the spawned daemon, even with my API.HTTPHeaders options set up inside the ipfsOptions, this is the error I get:

![image](https://user-images.githubusercontent.com/28849055/124840000-4c9acd00-df60-11eb-86e4-ac9a2b36f3c9.png)

If i reload the webui at the same time my app is starting it shows data and a succes message, just for a sec (if you change webui view it shows the error message again). I can't reproduce this right now.

**Reproduction**

```JavaScript
const { createController } = require('ipfsd-ctl')
const ipfsHttpModule = require('ipfs-http-client');
const ipfsBin = require.resolve('ipfs/src/cli.js');

export const getDataNode = async (port) => {
  const ipfsd = await createController({
    ipfsHttpModule,
    ipfsBin,
    remote: false,
    type: 'js',
    ipfsOptions: {
      config: {
        API: {
          HTTPHeaders: {
            "Access-Control-Allow-Origin": [
              "*"
            ],
            "Access-Control-Allow-Methods": ["PUT", "POST", "GET", "DELETE"],
            "Access-Control-Allow-Credentials": true,
          }
        }
      }
    }
  })
  console.log(ipfsd);
  return ipfsd.api
};
```

**Expected behavior**
Connet webui with my daemon.

**Screenshots**

**Desktop:**
 - OS: Win10
 - Browser: chrome
 - Version 2.11.4

**Comment by lidel** [comment]
@denyncrawford you need to enter either URL or Multiaddr:

>  ![Screenshot 2021-06-30 at 00-07-47 Settings IPFS](https://user-images.githubusercontent.com/157609/123873892-856eec80-d937-11eb-8cec-80b419e79356.png)

(we added the above hint in https://github.com/ipfs/ipfs-webui/pull/1811 and will ship in next version)

**Comment by denyncrawford** [comment]
@lidel This is what I have in that field:

![image](https://user-images.githubusercontent.com/28849055/124916591-36752700-dfc9-11eb-9c37-c28563179524.png)

The error is still the same:

![image](https://user-images.githubusercontent.com/28849055/124916645-455bd980-dfc9-11eb-8578-66ee5fc23fc9.png)

And this is how I have my addresses:

![image](https://user-images.githubusercontent.com/28849055/124916710-59074000-dfc9-11eb-9a60-89d865fa89d3.png)

Seems like it's not the solution, I have my gateway working, but the webui isn't :/ Thank you btw.

**Comment by lidel** [comment]
Ah, I just realized you are using js-ipfs (`type: 'js'`).
The latest version of webui does not support js-ipfs. 
I'm closing this as we are tracking fixing that  in https://github.com/ipfs/ipfs-webui/issues/1737

If you want to use webui  with js-ipfs, you need to use older version that is bundled with js-ipfs – it can be loaded via `http://127.0.0.1:{api_port}/webui`, in your case http://127.0.0.1:5001/webui

**Comment by denyncrawford** [comment]
Nah, it is the same version:

![image](https://user-images.githubusercontent.com/28849055/125107684-79152d00-e0b7-11eb-9786-f891d50a5477.png)
