### ISSUE TITLE
Download Broken - Tries To Use IPFS gateway at 0.0.0.0:8080

### ISSUE THREAD

**Issue by c0llab0rat0r** [ipfs/ipfs-webui#1821]
#### Version information:

go-ipfs version: 0.8.0-ce693d7
Repo version: 11
System version: amd64/linux
Golang version: go1.14.4

The above is from a container running docker tag ipfs/go-ipfs:v0.8.0, running on Ubuntu 20.04 LTS.

#### Description:

Browse to the admin web site (yourserver:5001), click on Files, click on the elipsis, and click Download. The download will fail.

If you use F12 in FireFox to open the networking tab and try again, you'll see a GET failure to 0.0.0.0:8080. Presumably, the web site is assuming that the IP address the gateway HTTP server is bound on is also an IP address it can use from the browser.

Since the IPFS gateway is running in a Docker container, it binds to 0.0.0.0, and does not know what the external IP address of its own IPFS gateway is. This would also apply if the IPFS gateway is behind a reverse proxy or NAT.

#### Suggested changes

* The web site should detect obvious incorrect information for the gateway (e.g. when it is 0.0.0.0) and alert the user. The web site already does this for detection of incorrect CORS configuration
* There should be an additional setting to specify the public address of its own gateway. If this setting already exists, the alert should describe how to configure it or refer the user to documentation on how to do it

A harsher option could be to require the new field to be populated when the gateway is bound to 0.0.0.0, but that wouldn't be backward compatible.

**Comment by SgtPooki** [comment]
We need to reproduce this and make sure we have documented the steps for doing so. We will then probably need to clarify what sort of messaging to provide to users (prompt them to update gateway configured in settings?) given an invalid gateway URL from go-ifps

**Comment by hadim** [comment]
I would also be interested in that feature since it will allow browsing and using a deployed ipfs container on a local network. For now the webui works fine but all the download fail.

**Comment by F-Node-Karlsruhe** [comment]
Using kubo in docker and there the gateway is 0.0.0.0 which is of course not reachable from the outside, but changing the gateway to the domain crashes kubo.

Can we make the gateway configurable in the frontend?

**Comment by wblondel** [comment]
I have the same issue, is there any workaround?

**Comment by lidel** [comment]
@wblondel workaround is updating configuration in `Addresses.Gateway` to have `/ip4/127.0.0.1/tcp/8080` instead of `/ip4/0.0.0.0/tcp/8080` and probably also to run docker with `--net=host` (NAT is not necessary, and only cripples your node's connectivity options).

Once fix from #2287 lands, this will no longer be necessary.
