### ISSUE TITLE
Support for custom public gateway links on the Explore page

### ISSUE THREAD

**Issue by shazz** [ipfs/ipfs-webui#1822]
Hi,

Would it be possible, to support private swarms, to have the "View on IPFS Gateway" url, in the Inspect view, configurable? 
In my case it would be great if it could point to my local gateway.

Edits:

- on Ubuntu, in the latest webui version it seems to use the ipfs configuration but when this one is set to: `"Gateway": "/ip4/0.0.0.0/tcp/8080"`, 0.0.0.0 points to at best localhost which is not the expected address
- on Windows 10, this link is always https://ipfs.io/ipfs/...

I don't understand why it differs between Linux (where the IPFS server is) and Windows (just a remote client)

Thanks !

**Comment by lidel** [comment]
I think this is doable with a little dev effort.

Support for setting a custom gateway shipped in https://github.com/ipfs/ipfs-webui/releases/tag/v2.13.0 but it is only used on Files screen ([FilePreview.js#L153-L154](https://github.com/ipfs/ipfs-webui/blob/675564e8b5990747a8e41ba5f22c65fdbdfe4f54/src/files/file-preview/FilePreview.js#L153-L154) etc)

We could add `selectPublicGateway` to [ExploreContainer.js](https://github.com/ipfs/ipfs-webui/blob/main/src/explore/ExploreContainer.js) and pass it to `ipld-explorer-components` so it shows two options (local gw and public gw). 
This requires changes to upstream https://github.com/ipfs/ipld-explorer-components but is a sensible feature to implement, if someone has bandwidth to submit PR there.
