### ISSUE TITLE
bug: docker `ipfs/go-ipfs:latest` webui `could not connect to IPFS api` however ipfs gateway is working fine 

### ISSUE THREAD

**Issue by sabotagebeats** [ipfs/ipfs-webui#1823]
**Describe the bug**
Docker webui unable to connect to api 
**To Reproduce**
`docker run -d --name ipfs_host -v ~/ipfs/staging:/export -v ~/ipfs/ifps:/data/ipfs -p 4001:4001 -p 8080:8080 -p 5001:5001 ipfs/go-ipfs:latest`

**Expected behavior**
docker webui connects and shows peers

**Screenshots**
![image](https://user-images.githubusercontent.com/27985126/126713696-884892da-0f35-4b09-820e-9599bc8d4fb6.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS server
 - Browser: chrome on locally networked desktop
 - Version: latest docker

**Comment by sabotagebeats** [comment]
despite API not working locally on the node, ipfs is working fine on this node: 
![image](https://user-images.githubusercontent.com/27985126/126714052-740b6ed5-4908-4e41-8674-15f7df67e02a.png)

**Comment by lidel** [comment]
`https://127.0.0.1:5001/ipfs` is invalid addres, please use `https://127.0.0.1:5001` :)
