### ISSUE TITLE
Is there a way to get a custom shareable link but omitting ensureMFS function?

### ISSUE THREAD

**Issue by feliciss** [ipfs/ipfs-webui#1827]
**Is your feature request related to a problem? Please describe.**
try to get a custom shareable link.

**Describe the solution you'd like**
replace ipfs.io to a custom gateway link in action.js file.

**Describe alternatives you've considered**
Call connect functions to omit ensureMFS function.

**Additional context**
I'm not a frontender.

**Comment by lidel** [comment]
There is no way right now, but we are tracking this feature request in https://github.com/ipfs/ipfs-webui/issues/1717
