### ISSUE TITLE
Throttle IPFS_INIT_FAILED events

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1831]
## Problem

When user opts-in to sending usage metrics, and ipfs-webui is not able to connect to HTTP API, it will send a new `IPFS_INIT_FAILED` event to Countly every few seconds when it tries to reconnect and fails again. This produces multiple events sent every minute:

> ![2021-07-31--00-56-47](https://user-images.githubusercontent.com/157609/127720851-89db70d8-b4ab-4009-a77f-0f264f6dbb9d.png)

This behavior can be observed on [https://webui.ipfs.io](https://webui.ipfs.io/) and inside of  ipfs-desktop when a local node is shut down when webui is still open (need to opt-in to metrics first)

Additionally, on a slower machine ipfs-desktop shows ipfs-webui before go-ipfs is fully booted, but that triggers no more than one or two events.

## Solution

We should be throttling how often `IPFS_INIT_FAILED` is sent.

Some quick ideas:
- We want to decrease noise of situations where node started within a few seconds (either automatically in ipfs-desktop or manually when user forgot to run it) 
   -  Idea: do not send send it immediately, but keep buffering events and  wait for `IPFS_INIT_FAILED` state to remain for 10+ seconds.
 - When  `IPFS_INIT_FAILED` is confirmed by being real for over 10 seconds, we do not want to keep  spamming events every few seconds.
   - Idea: send it only once every 5 minutes (memoize send function for 5min)

```[tasklist]
### Tasks
- [ ] prevent sending more than 1 IPFS_INIT_FAILED event per user per app load
- [ ] Ensure IPFS_INIT_FAILED events are being logged to error.log
```

**Comment by SgtPooki** [comment]
💯 We should separate the IPFS_INIT_FAILED metric from retry failures. 

When I first saw the IPFS_INIT_FAILED metric, I thought it was supposed to only fire once for each user, for each app instance run, and I think that intuition should be codified. Retries continuing to fail are valid, but should be captured via a different metric.

**Comment by SgtPooki** [comment]
code search results: https://github.com/search?q=repo%3Aipfs%2Fipfs-webui%20IPFS_INIT&type=code
