### ISSUE TITLE
Want to participate in the Japanese localization of the IPFS Web UI.

### ISSUE THREAD

**Issue by rarafy** [ipfs/ipfs-webui#1848]
## Problem
I would like to participate in the __Japanese__ localization of the __IPFS Web UI__.
However, as you can see in the image, Japanese is not shown as an option.
How can I participate in the project?

![image](https://user-images.githubusercontent.com/33755507/132562575-448cb98d-3bb3-4ff4-b4ea-28fe28639b01.png)

**Comment by lidel** [comment]
@rarafy you've been added to the translation team, thank you for your contributions! :pray:
