### ISSUE TITLE
Would like to be a reviewer for the Japanese localization of the IPFS Web UI.

### ISSUE THREAD

**Issue by rarafy** [ipfs/ipfs-webui#1851]
I was appointed as a translator in #1848 and I finished translating all one screen.
However, there are a large number of translations awaiting review, and we have not yet committed them.
So, I would like to become a reviewer and scrutinize these translations, can you appoint me?

![image](https://user-images.githubusercontent.com/33755507/132876935-4be28e7a-4db2-4b21-8404-cc097ca066a5.png)

**Comment by rarafy** [comment]
Some of the translations seem to be awaiting review for several years, and there is room for improvement.
Thanks in advance!

![image](https://user-images.githubusercontent.com/33755507/132877872-1877afb2-3c64-4aa3-b484-1e10586cfaee.png)

**Comment by lidel** [comment]
@rarafy Review step is optional, it freezes "good" translations  from being changed, but without it strings are still used in the app.

Happy you want to do additional due diligence – you should have Reviewer status now. 
Thank you for you contributions! :pray:
