### ISSUE TITLE
Add option for `--nocopy` flag for importing files in the web UI if it detects `filestore` is enabled in the config

### ISSUE THREAD

**Issue by AccessViolation95** [ipfs/ipfs-webui#1855]
**Is your feature request related to a problem? Please describe.**
I cannot import files using the `--nocopy` from flag from the web UI.

**Describe the solution you'd like**
If `Experimental.FilestoreEnabled` is set to `true` in the go-ipfs config, there should be a check mark when importing files that uses the `--nocopy` flag to ensure the file is not duplicated.

**Describe alternatives you've considered**
The alternative solution has been using the command line; `ipfs files cp /ipfs/$(ipfs add -Q --nocopy <local-file>) "/<dest-name>"`

**Comment by Stebalien** [comment]
Unfortunately, this isn't possible. For security reasons, the browser won't tell the WebUI where the files live on-disk.

If you need the Filestore, you'll need to use the CLI.
