### ISSUE TITLE
Status page: show agent version suffix

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1862]
Ref.  https://github.com/ipfs/ipfs-desktop/pull/1914  https://github.com/brave/brave-browser/issues/18505

```
go-ipfs/0.10.0/desktop
```

We should show the suffix on the Status page to make it easier to eyeball which node type is in use.
This could be useful in Brave, IPFS Desktop scenarios, but also when power users customize it on their own via `ipfs daemon --agent-version-suffix=foo`

**Comment by xrazis** [comment]
Took the liberty and did it anyways, after messing my repos history a bit :P.
