### ISSUE TITLE
Webserver does not work remotely.

### ISSUE THREAD

**Issue by nigeljohnson73** [ipfs/ipfs-webui#1868]
**Describe the bug**
When attempting to access the webserver from anywhere other than localhost and I get a connection refused. When I do a port forward of 5001 using `ssh -L 5001 127.0.0.1:5001 pi@myhost` I get a shell of a web page, but a lot of JSON files missing in the network section, and all the API requests show a 403 - not permitted. Doing this without setting the CORS is a different error (explaining that the requests we blocked by CORS) so I have set that correctly as per the messages on the page that shows in the browser.

**To Reproduce**
* On the server set up CORS to 0.0.0.0 for POST, GET, PUT (covers all web eventualities)
* I also set up the ENABLE_WALLET_REMOTE flag before starting the daemon
* Connect to http://hostname:5001/webui in another browser on another host
* XXX Get connection refused message
* Connect an SSH session `ssh -L 5001 127.0.0.1:5001 pi@myhost`
* connect to http://127.0.0.1:5001/webui in the original browser
* XXX Get the page shown below (webserver correctly servicing lots of requests and no CORS issues) but json files won't return and nor will any API call

**Expected behavior**
* Connecting from anywhere in my LAN should allow access - update the web server config to listen on all public interfaces, but I can't find the config files to check
* Connecting over ssh with 5001 forwarded should NOT have 403 permission issues

**Screenshots**
![image](https://user-images.githubusercontent.com/6493525/138282419-f5f162f7-c7fc-4c98-9492-292ce30b501c.png)

**Desktop (please complete the following information):**
 - OS: Linux ARM (Rasbian - lite) and running browser on MacOS and Windows 10
 - Browser Chrome
 - Version 94 Chrome clients on Windows 10 and MacOS big SUR, host on Rasbian 10, btfs version 1.5.2

**Additional context**

**Comment by lidel** [comment]
@nigeljohnson73 seems that you are using BTFS, which is not **IPFS**.
This is **IPFS-webui**. Please fill issue in https://github.com/TRON-US/btfs-webui.
