### ISSUE TITLE
Welcome page error

### ISSUE THREAD

**Issue by sad-leo** [ipfs/ipfs-webui#1873]
Describe the bug
The private chain is built, why the homepage can’t be loaded when it is not connected to other network nodes

Screenshots
![image](https://user-images.githubusercontent.com/42138514/141936554-c0473c5c-0fe6-49f3-8e01-3956d615ac15.png)

Desktop (please complete the following information):

OS:  windows 10
Browser: Edge

**Comment by lidel** [comment]
Seems that you've set up private network (https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) – is that correct?
If so, you can only fetch data from peers who share the same key. Try disabling private network and see if the data you are trying to see can be fetched from the public swarm, or import it manually to your private swarm via `ipfs dag export/import`.
