### ISSUE TITLE
I can't reliably upload files.

### ISSUE THREAD

**Issue by holdengreen** [ipfs/ipfs-webui#1876]
I'm trying to use the webui to upload batches of files into a folder/directory but that fails red X's.

**To Reproduce**
1. Go to a folder.
2. Click on '+Import'
3. Pick 'File'
4. Select multiple files  and confirm

**Expected behavior**
I expect that the files will take a short time to upload to the server and I should receive visual confirmation.

Firefox console output:
```
Error: Promised response from onMessage listener went out of scope chrome.js:92:30
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5001/api/v0/stats/bw. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5001/api/v0/add?stream-channels=true&pin=false&wrap-with-directory=false&progress=false. (Reason: CORS request did not succeed).

Uncaught (in promise) HTTPError: 
    Babel 3
        o
        t
        exports
    n error.js:24
    e core.js:91
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 6
    O core.js:73
    e http.js:147
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 6
    value 5.46be50cc.chunk.js:2
    fetch core.js:192
    value http.js:175
    t add-all.js:36
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 6
    e index.js:9
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 4
    a index.js:9
    R actions.js:603
    n actions.js:278
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 4
    e utils.js:87
    l runtime.js:63
    _invoke runtime.js:293
    x runtime.js:118
    Babel 4
construct.js:19:20
```
And I'm getting some weirder and maybe more useful output in Chrome.

**Desktop**
 - OS: Manjaro Linux, kernel 5.10
 - Browser Firefox
 - Version 94

**Additional context**

I'm using a remote web server and forwarding the ports '5001', '8080' (which isn't working correctly), '3000' and '4001' to my laptop.

The daemon is running on a 500GB Storage VPS from Time4VPS and it's running Debian 9 with an ancient 2.6.32 kernel on OpenVZ 6.

**Comment by holdengreen** [comment]
If this isn't a good place I can post on discuss.ipfs.io

I'm likely doing something wrong

**Comment by SgtPooki** [comment]
@holdengreen Thanks for the detailed information about your remote server and daemon.

You say that you're forwarding ports, but you say "(which isn't working correctly)." Can you clarify what you mean by this? Also, I see CORS errors in the output. Did you follow the instructions at https://github.com/ipfs/ipfs-webui#configure-ipfs-api-cors-headers ?

**Comment by lidel** [comment]
Also: what is the URL you use in your browser to load the webui itself? 
- `http://127.0.0.1:5001/webui` ? (:information_source: this one should not require CORS, as you load safelisted version from API port)
- https://webui.ipfs.io or `http://webui.ipfs.io.ipns.localhost:8080` ?  (:information_source: this one requires CORS setup because of different origin than port :5001)

**Comment by holdengreen** [comment]
I remember only needing to forward the web port, yes I go to `http://127.0.0.1:5001/webui`.
I'll get back to this.
