### ISSUE TITLE
IPNS and DNSLink fail to load in the explore tab

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/ipfs-webui#1884]
**Describe the bug**
When typing things like `/ipns/k51...`, `/ipns/ipfs.io` into the browse/inspect bar if you hit inspect it'll take you to the explore page and will error.

This bug might be related to explore.ipld.io more than here, but since we depend on similar components I'm filing here. Feel free to move or redirect.

There are a variety of errors depending on the mutable identifier type:
- `/ipns/k51...` -> Error: No resolver found for codec "libp2p-key"
- `/ipns/12D3...` -> HTTPError: invalid path "12D3K...": selected encoding not supported
- `/ipns/Qm...` -> Seems to hang/break things (but could be mistaken)
- `/ipns/ipfs.io` -> Error: invalid character '.' in 'ipfs.io'

**To Reproduce**
1. Go to Status Page
2. Click on Browse bar
3. Type in one of the paths above and click the Inspect button

**Expected behavior**
IPNS resolution should work (i.e. resolve the IPNS path to the IPFS path and continue as normal). Alternatively some error like "IPNS not supported" would work and turn the rest of this into a feature request.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windowsd 10
 - Browser: Chrome
 - Version 96

**Comment by lidel** [comment]
This is a sensible feature. 
At the very minimum, anything other than CID or `/ipfs/CID/...` should get resolved to an immutable content path.

**Comment by SgtPooki** [comment]
related: https://github.com/ipfs/ipfs-webui/issues/1076

**Comment by SgtPooki** [comment]
closing in favor of https://github.com/ipfs/ipld-explorer-components/issues/400
