### ISSUE TITLE
Downloading Multiple Large Files Fails

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-webui#1885]
**Describe the bug**

Downloading large files fails due to the usage of `ipfs object add-link`. See https://github.com/ipfs/go-ipfs/issues/7421.

**To Reproduce**

1. Go to Files
2. Click on multiple large files
3. Click on 'Download'

**Expected behavior**
Download the files.

**Additional context**

See https://github.com/ipfs/go-ipfs/issues/7421. We should move to the MFS API, perhaps through some kind of temporary file on the MFS? 

Perhaps something such as `/temp/Download {timestamp}`. cc @lidel

**Comment by lidel** [comment]
@hacdias yes, our only option is MFS at the moment. My thinking:

- create directory named `/zzzz_{timestamp}` (so it is at the end of file list – minimizes the risk of UI jitter in case React refreshed file list that exact moment ;))
- `cp` references to files there
- copy CID of the zzzz directory (ipfs files stat)
- start download of the archive with CID contents
- remove the zzzz directory (safe to do asynchronously after the download already started, even if GC is enabled, the root block server its purpose)
