### ISSUE TITLE
File → menu → Download buffers entire file into a blob

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-webui#1887]
- OS: Windows 10 x64
 - Version of IPFS Desktop [0.18.1]

**Describe the bug**

https://streamable.com/9z175t

**To Reproduce**
1. Go to the file
2. Click on more
3. Scroll down to Download
4. Blank Screen after some seconds.

**Log files:**

[combined.log](https://github.com/ipfs/ipfs-desktop/files/7834484/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/7834485/error.log)

**PD:** I tried reinstalling, but same problem.

**Comment by hacdias** [comment]
@lidel I think one of the issues is the directory: there's no way of downloading a directory via the gateway and the API is POST only (unless that changed recently).

**Comment by lidel** [comment]
@hacdias afaik `/api/v0/get` is also exposed on Gateway port, and there it should accept GET (POST restriction applies only to the RPC API port).  
I think is fine to use that until we have a better way for fetching directories on Gateways.
