### ISSUE TITLE
no ipfs commmands in terminal on fedora 35

### ISSUE THREAD

**Issue by Eris7090** [ipfs/ipfs-webui#1888]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I try to use ipfs in the terminal but it doesn't work...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lidel** [comment]
See https://docs.ipfs.io/install/command-line/
