### ISSUE TITLE
Popup on bandwidth graph shows wrong numbers

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-webui#1892]
- OS: Windows
 - Version of IPFS Desktop 0.18.1

**Describe the bug**
The hover-popup for the bandwidth graph is showing numbers which are WAY off what's shown in the graph at that point in time.

**To Reproduce**
1. Move the mouse on a point in the graph
2. See error

**Expected behavior**
No bug.

**Screenshots**
![IPFS Bandwidth popup bug](https://user-images.githubusercontent.com/614929/149411581-94bea9d4-7a8c-456b-b679-37635c2e1a70.png)

**Comment by lidel** [comment]
It looks fixed in 0.19?

> ![2022-02-25_03-06](https://user-images.githubusercontent.com/157609/155640051-0c543d8b-971c-4b5e-bf23-cf01df921f61.png)

@RubenKelevra mind confirming?
