### ISSUE TITLE
Translation/zh/app.json report 404

### ISSUE THREAD

**Issue by akimoto72738** [ipfs/ipfs-webui#1899]
**Describe the bug**

> ![image](https://user-images.githubusercontent.com/67720156/152377619-ad1924a1-a692-45ca-9256-a9f52088da24.png)

**I check the source file and find that there is no path named "zh", only "zh_CN"**
**WebUI version 2.14.0**

> ![image](https://user-images.githubusercontent.com/67720156/152378581-aafa1cc4-8736-449c-a122-b8b0f71e8be2.png)

**Another problem is that I can not upload any folder to ipfs node by webui**

> ![image](https://user-images.githubusercontent.com/67720156/152380116-960950d9-2f1f-4dea-898c-9aff969eb2f2.png)

**PS: this error may be caused by nginx reverse proxy, and also, I found  a error from nginx logfile.**
**hope someone can help me, thank you**

```
2022/02/03 15:40:41 [error] 227964#0: *182369 upstream timed out (110: Connection timed out) while reading upstream, client: 172.16.1.120, server: www.abc.com, request: "POST /api/v0/add?stream-channels=true&pin=false&wrap-with-directory=false&progress=false HTTP/2.0", upstream: "http://172.16.1.109:5001/api/v0/add?stream-channels=true&pin=false&wrap-with-directory=false&progress=false", host: "api.abc.com", referrer: "https://www.abc.com/"
```

**Comment by lidel** [comment]
@akimoto72738  those 404 are harmless – it's webui trying to determine locale file based on locale supported by your browser:
- https://github.com/ipfs/ipfs-webui/blob/main/src/i18n.js#L36-L40 

As you can see, we have fallback defined: if `zh` is not found, 
it should try `zh-CN` and if that is not available, do final fallback to English. 

So my question is: 
- Did it load `zh-CN` or did it load English for you?
- Can you see failed 404 for `zh-CN` ?

**Comment by akimoto72738** [comment]
@lidel, understood

- Did it load zh-CN or did it load English for you?

> Yes, Chinese Translation loading normally

- Can you see failed 404 for zh-CN ?

> No, I can not see any 404 for zh-CN
