### ISSUE TITLE
Pinning to Pinata disabled due to "Rate limit exceeded"

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-webui#1900]
- OS: Windows
 - Version of IPFS Desktop 0.18.1

**Describe the bug**
Pinata integration stopped working. So it worked before and after some update in the recent past it stopped working. I thought it's a temporary outage as I saw it first. But that's quite a while ago, maybe a month or two, and it's still not working.

**To Reproduce**
1. -> Settings
2. Click "+ Add Service"
3. Select Pinata
4. Go to Pinata's API page (which is linked)
5. Create a new key
6. Add it to the dialog opened in step 3
7. Click on Save
8. Pinata's status is "Pins: Failed to fetch"

**Expected behavior**
The integrated service connection should work.

**Screenshots**
![IPFS Desktop Pinata fail](https://user-images.githubusercontent.com/614929/149426619-c2b821f3-9f44-4163-a540-22a9b1e2af43.png)

**Comment by lidel** [comment]
Ok, scratch it. This won't be enough by any means.

The _Files_ screen will check and cache remote pin status for every file  on the screen. 
The status is cached until browser tab with ipfs-webui is closed (or ipfs-desktop is shut down and started again), or file is oubbed/unpinned by the user via webui.

This is what triggers the throttling – 6 requests per minute is not enough.

We send 10 CIDs per request  and I can easily generate more than 10 HTTP requests while visiting a bigger directory for the first time:

> ![2022-02-08_00-07](https://user-images.githubusercontent.com/157609/152887363-3b326b07-973d-4dc5-b7e1-f988f422cb48.png)
> (here one can see that estuary responds,  but Pinata does not because of throttling its marked as offline)


Will see if we can do anything about this (eg. send 100 CIDs in one request), or run checks in throttled queue when checking status for pinata.

**Comment by lidel** [comment]
@RubenKelevra recent changes in ipfs-webui [v2.15.0](https://github.com/ipfs/ipfs-webui/releases/tag/v2.15.0)  should restore remote pinning functionality even when using throttled service like Pinata (which I confirmed to be 6 requests per minute).

You can try it at https://webui.ipfs.io (needs CORS safelisting), it will also ship in future release of [ipfs-desktop](https://github.com/ipfs/ipfs-desktop/commit/4ff45f229e5bc15c481e489b8a772f13797149c3)  (0.19+) and [go-ipfs](https://github.com/ipfs/go-ipfs/pull/8712) (0.13+)

**Comment by RubenKelevra** [comment]
Thanks for the fast fix! :)

**Comment by SgtPooki** [comment]
@lidel can we remove the pinned flag?

**Comment by acostaedg** [comment]
This issue is still happening in latest kubo version:

AGENT	kubo v0.15.0-rc1 d577980/docker
UI	        [v2.15.1](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.15.1)

When Pinata is added as remote pinning service it hits rate limit right away. Can this issue be re-opened? or if any workaround exist can someone please suggest?
