### ISSUE TITLE
Settings show 0 local pins

### ISSUE THREAD

**Issue by rayswchiu** [ipfs/ipfs-webui#1906]
i've recently uninstall/re-install IPFS Windows (Windows 10). 

i recall that there was a directory like "IPFS-Desktop" in my previous installation, but not the current one (see screenshot)
![Untitled](https://user-images.githubusercontent.com/31142321/154060972-09109cbc-3af3-4727-9962-9ed03ed35383.png)

i pinned the whole directory on my IPFS Windows and it shows ok on the Files page, but NOT on the Settings Page
![Untitled](https://user-images.githubusercontent.com/31142321/154061241-e80712ff-21ab-4942-9953-1ffe05012c60.png)

Is this normal or did it miss anything?

**Comment by lidel** [comment]
Thank you for reporting, I think there is a bug on _Settings_ screen which always show Local pin count to be 0.

**Comment by hacdias** [comment]
Fix in #1911
