### ISSUE TITLE
Add DHT PROVIDE function to file popup menu

### ISSUE THREAD

**Issue by hsn10** [ipfs/ipfs-webui#1913]
**Is your feature request related to a problem? Please describe.**
Files are often not found in DHT if you have _larger_ node size because it takes too much time to announce all local blocks and they are expiring from DHT faster then they are announced. They expire after 1 day and it takes more then 1 day to announce all local blocks.

**Describe the solution you'd like**
Add "DHT PROVIDE" function to file popup menu current with items like: COPY CID, SHARE LINK, DOWNLOAD, RENAME, REMOVE. This will allow to announce specific file to DHT and make it easier found by other people. Use case is if you are going to share some IPFS link in forum, it will be better to explicitly announce it to DHT so gateways will find and load it faster.

**Describe alternatives you've considered**
alternative is to use command line _ipfs dht provide_ - I am doing it now but it slow down work.

**Comment by lidel** [comment]
### Workaround: manually enable Accelerated DHT Client

If your repo is so big that you can't provide fast enough, consider enabling 
[Accelerated DHT Client](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#accelerated-dht-client).

### Solving root problem

Bolting on "DHT provide all blocks behind this file/directory"  is a band-aid, and will be extremely confusing thing to add to UI that is included in places like IPFS Desktop and Brave browser (why there is manual provide ? does it mean if i dont click it everything is private? etc)

I'd rather enable accelerated DHT client automatically when a repo is above some size and unable to provide all blocks. Understanding when we should enable it is the first step.

@hsn10 mind answering below, so we understand what repo size hits the problems you described?
- what is the size of your repo and how many CIDs are you providing? 
  - provide the output of `ipfs repo stat` command

**Comment by hsn10** [comment]
Accelerated DHT Client is unuseable, it creates thousands of threads effectively stopping all other workloads on machine while working - it is doing 10 minutes long batches.

**Comment by lidel** [comment]
@hsn10 mind answering the question from the end of my  last comment (`ipfs repo stat` output)?

**Comment by hsn10** [comment]
450k objects

**Comment by SgtPooki** [comment]
@hsn10 the command `ipfs repo stat` should return output that looks like this:

```
> ipfs repo stat                                                                                                                                                                                       
NumObjects: 9468
RepoSize:   614527384
StorageMax: 10000000000
RepoPath:   /Users/sgtpooki/.ipfs
Version:    fs-repo@12
```

**Comment by lidel** [comment]
In case anyone wants to PR to add this,  this should be hidden by default and displayed only when "advanced user" checkbox is checked on _Settings_ page. We don't have such checkbox, so it needs to be added as well, below CLI Tutor.
