### ISSUE TITLE
UI for indicating a big, sharded directories

### ISSUE THREAD

**Issue by Helletons** [ipfs/ipfs-webui#1917]
**Describe the bug**
I am trying to upload 6666 files. There should be a link for every file once the upload has completed but only 256 are appearing every time. When I open the folder itself all 6666 png files are there.
I have tried gradually uploading the files into the folder as well as uploading the folder all at once.

**To Reproduce**
1. Go to Files
2. Click on Import > New Folder. Gradually drag png files into the folder.
3. Once finished, click on the three dots next to the folder and "Inspect"
4. See only 256 links instead of the thousands that should have generated.

1. Go to Files
2. Click on Import > Folder. Add chosen folder
3. Once finished, click on three dots next to the folder and "Inspect"
4. See only 256 links instead of the thousands that should have generated.

**Expected behavior**
What I expect to happen is that when I import 6666 files (or however many thousand) that I see 6666 links in the Inspect screen

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.6.1
 - Browser n/a
 - Version IPFS Desktop 0.20.3

**Comment by lidel** [comment]
My guess is that the manifest of the directory you create gets bigger than the maximum block limit in IPFS, and that forces it to be automatically sharded.

The 256 children you see is only the first level of HAMT shard.


Can you confirm the directory you open in IPLD Explorer has hamt-sharded type as seen below?

| normal dir | sharded dir | 
| ---- | ---- |
| ![2022-04-11_20-53](https://user-images.githubusercontent.com/157609/162809953-508f84eb-2d82-437b-8e0e-56a457efc389.png) |  ![2022-04-11_20-53_1](https://user-images.githubusercontent.com/157609/162810000-84a41543-059d-453b-8ce5-f1f627f4b947.png) |

If so, this works as expected – Inspect view gives you an insight into real, low-level  representation of a big directory. To see the actual files, you need to go two or more levels deep.

**Comment by SgtPooki** [comment]
@Helletons we'll leave this issue open just in case the community wants to add this support. If you're still blocked please reach out.

**Comment by Helletons** [comment]
Hi

Sorry for the slow response. Yes you were correct. It was sharded and actually all fine.
The tutorial I had watched suggested it would show a long list of every file immediately
instead of this sharded version. All fine

Thanks for getting back to me :)

April 11, 2022 8:59:09 PM CEST Marcin Rataj ***@***.***> wrote:

My guess is that the manifest of the directory you create gets bigger than the maximum block limit in IPFS, and that forces it to be automatically sharded.
The 256 children you see is only the first level of HAMT shard.
Can you confirm the directory you open in IPLD Explorer has hamt-sharded type as seen below?normal dirsharded dir
If so, this works as expected – Inspect view gives you an insight into real, low-level  representation of a big directory. To see the actual files, you need to go two or more levels deep.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email

**Comment by tinytb** [comment]
Last message from reporter indicates it's actually all fine. Closing.
