### ISSUE TITLE
404 Error when viewing 'Files'. Can't acces existing uploaded items

### ISSUE THREAD

**Issue by bluebob1** [ipfs/ipfs-webui#1927]
**Describe the bug**
I have uploaded a large amount of content onto 'IPFS Desktop' without struggle, untill recent when it gave me a "404" message when accessing the 'Files'-tab. It states that there are no documents to be found but it still shows that 35Gb is in use. So my files are still present but I can not see nor access them through the 'Files'-tab.

I also installed the 'Companion'-addon, from which i can still upload more files but can still not view anything & still get the 404 message.

**Expected behavior**
I should see my Folders/Files but get a '404'-path and statement that there are no files yet.

**Screenshots**
<img width="1775" alt="Screenshot 2022-04-26 at 11 41 13" src="https://user-images.githubusercontent.com/32448223/165271600-79380e02-0fa0-4ed6-968a-393cbf05a0a1.png">

<img width="1788" alt="Screenshot 2022-04-26 at 11 45 54" src="https://user-images.githubusercontent.com/32448223/165272489-af47d0f3-a95d-42b4-9235-968817f9da1a.png">

**Desktop (please complete the following information):**
 - OS: [Mac iOS]
 - Browser [Chrome]
 - Version [v0.20.5]

**Additional context**
I have tried downgrading the version to v0.20.4 & .3 but the issue remains.

**Comment by SgtPooki** [comment]
@bluebob1 this problem occurs when there are a large number of files in your repo. There is an issue open related to this, https://github.com/ipfs/ipfs-webui/issues/1861. I'll close this issue in favor of that one.
