### ISSUE TITLE
IPFS client can't connet to internet

### ISSUE THREAD

**Issue by blockchainx** [ipfs/ipfs-webui#1947]
**Describe the bug**
IPFS client shows "can't connect to IPFS API".

**To Reproduce**
1. Click to start IPFS client.

**Expected behavior**
IPFS client run to connect to internet successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/19857992/173743508-43dc5c78-7692-413f-b301-adf823c662cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version v2.15.0

**Comment by SgtPooki** [comment]
@blockchainx thanks for submitting this issue. Please see https://github.com/ipfs/go-ipfs/issues/8911#issuecomment-1108972675
