### ISSUE TITLE
VersionMismatch: Unsupported daemon version '0.13.0' (not in range: 0.4.23 ≤ … < 0.8.0)

### ISSUE THREAD

**Issue by deepasoman93** [ipfs/ipfs-webui#1954]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SgtPooki** [comment]
Hi @deepasoman93, it looks like you didn't fill out the issue report, so we cannot really help much here. Would you mind filling out the issue template with the relevant details so we can help you?
