### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by phojz** [ipfs/ipfs-webui#1975]
when i run "npm install"

my node version is v16.12.0,npm is 8.1.0

Errors are reported as follows：

```
npm ERR! code 1
npm ERR! path /Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js || node-gyp rebuild
npm ERR! info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.12.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mengfanxu/Library/Caches/node-gyp/16.12.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mengfanxu/Library/Caches/node-gyp/16.12.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mengfanxu/Library/Caches/node-gyp/16.12.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR!
npm ERR!
npm ERR!
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion
npm ERR!     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
npm ERR!     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
npm ERR! gyp.common.GypError: Error 1 running xcodebuild
npm ERR!
npm ERR! During handling of the above exception, another exception occurred:
npm ERR!
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 639, in gyp_main
npm ERR!     generator.GenerateOutput(flat_list, targets, data, params)
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2461, in GenerateOutput
npm ERR!     part_of_all=qualified_target in needed_targets,
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 840, in Write
npm ERR!     self.Pchify,
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1306, in WriteSources
npm ERR!     configname, arch=config.get("xcode_configuration_platform")
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 662, in GetCflags
npm ERR!     archs = self.GetActiveArchs(self.configname)
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 512, in GetActiveArchs
npm ERR!     xcode_archs_default = GetXcodeArchsDefault()
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 119, in GetXcodeArchsDefault
npm ERR!     xcode_version, _ = XcodeVersion()
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion
npm ERR!     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion
npm ERR!     return re.search(regex, output).groupdict()["version"]
npm ERR! AttributeError: 'NoneType' object has no attribute 'groupdict'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb
npm ERR! gyp ERR! node -v v16.12.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok
```

**Comment by lijinrui123** [comment]
> when i run "npm install"
> 
> my node version is v16.12.0,npm is 8.1.0
> 
> Errors are reported as follows：
> 
> npm ERR! code 1 npm ERR! path /Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb npm ERR! command failed npm ERR! command sh -c node ./scripts/install.js || node-gyp rebuild npm ERR! info install installing standalone, skipping download. npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@8.2.0 npm ERR! gyp info using node@16.12.0 | darwin | x64 npm ERR! gyp info find Python using Python version 3.7.3 found at "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3" npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 npm ERR! gyp info spawn args [ npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py', npm ERR! gyp info spawn args 'binding.gyp', npm ERR! gyp info spawn args '-f', npm ERR! gyp info spawn args 'make', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb/build/config.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/Users/mengfanxu/Library/Caches/node-gyp/16.12.0/include/node/common.gypi', npm ERR! gyp info spawn args '-Dlibrary=shared_library', npm ERR! gyp info spawn args '-Dvisibility=default', npm ERR! gyp info spawn args '-Dnode_root_dir=/Users/mengfanxu/Library/Caches/node-gyp/16.12.0', npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp', npm ERR! gyp info spawn args '-Dnode_lib_file=/Users/mengfanxu/Library/Caches/node-gyp/16.12.0/<(target_arch)/node.lib', npm ERR! gyp info spawn args '-Dmodule_root_dir=/Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb', npm ERR! gyp info spawn args '-Dnode_engine=v8', npm ERR! gyp info spawn args '--depth=.', npm ERR! gyp info spawn args '--no-parallel', npm ERR! gyp info spawn args '--generator-output', npm ERR! gyp info spawn args 'build', npm ERR! gyp info spawn args '-Goutput_dir=.' npm ERR! gyp info spawn args ] npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'. npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'. npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'. npm ERR! npm ERR! npm ERR! npm ERR! Traceback (most recent call last): npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion npm ERR! version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines() npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet npm ERR! raise GypError("Error %d running %s" % (job.returncode, cmdlist[0])) npm ERR! gyp.common.GypError: Error 1 running xcodebuild npm ERR! npm ERR! During handling of the above exception, another exception occurred: npm ERR! npm ERR! Traceback (most recent call last): npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in npm ERR! sys.exit(gyp.script_main()) npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 662, in script_main npm ERR! return main(sys.argv[1:]) npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 654, in main npm ERR! return gyp_main(args) npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/**init**.py", line 639, in gyp_main npm ERR! generator.GenerateOutput(flat_list, targets, data, params) npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2461, in GenerateOutput npm ERR! part_of_all=qualified_target in needed_targets, npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 840, in Write npm ERR! self.Pchify, npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1306, in WriteSources npm ERR! configname, arch=config.get("xcode_configuration_platform") npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 662, in GetCflags npm ERR! archs = self.GetActiveArchs(self.configname) npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 512, in GetActiveArchs npm ERR! xcode_archs_default = GetXcodeArchsDefault() npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 119, in GetXcodeArchsDefault npm ERR! xcode_version, _ = XcodeVersion() npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion npm ERR! version = CLTVersion() # macOS Catalina returns 11.0.0.0.1.1567737322 npm ERR! File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion npm ERR! return re.search(regex, output).groupdict()["version"] npm ERR! AttributeError: 'NoneType' object has no attribute 'groupdict' npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1 npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:16) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:390:28) npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) npm ERR! gyp ERR! System Darwin 21.5.0 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" npm ERR! gyp ERR! cwd /Users/mengfanxu/ltcompony/ipfs-webui/node_modules/iltorb npm ERR! gyp ERR! node -v v16.12.0 npm ERR! gyp ERR! node-gyp -v v8.2.0 npm ERR! gyp ERR! not ok

**Comment by lijinrui123** [comment]
To specify node version why

**Comment by lijinrui123** [comment]
@phojz 朋友留个联系方式加个好友呗 我这边也看这个项目呢

**Comment by JustinTime42** [comment]
I had this same issue. First, I just cloned the repo and ran `npm install`. 
Then, when I realized I was using the wrong version of Node and NPM, I set the correct versions and tried again, leading to more errors. Eventually I just deleted the whole repo, cloned it again, still with no success. Then I ran `npm update --legacy-peer-deps` and still no success. 

Then, just for kicks, I spun up an Ubuntu install on VirtualBox (was using windows 10 above). Once again got the same errors but this time when I tried `npm update --legacy-peer-deps` it worked.

**Comment by SgtPooki** [comment]
Thanks for submitting these issues and your npm error logs. If you could include your OS and 

We are currently experiencing multiple build issues due to out of date dependencies and unsupported npm/node versions and have forced using npm 8.1.0 and node 16.12.0 for the time being. For other install errors, I will be looking into those today, starting with fixing missing dependencies.

I recommend trying to install with [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci) instead of `npm install` for the time being.

**Comment by SgtPooki** [comment]
You can also see our nodejs/npm/platform support for builds at https://github.com/ipfs/ipfs-webui/actions/runs/2685408403

**Comment by SgtPooki** [comment]
@phojz @lijinrui123 @JustinTime42 can you all please pull the latest from main and try to install after clearing out your node_modules folder?

**Comment by phojz** [comment]
@lijinrui123  绿色软件 pho_jz

**Comment by phojz** [comment]
> @phojz @lijinrui123 @JustinTime42 can you all please pull the latest from main and try to install after clearing out your node_modules folder?

my os version is 12.4 (macOS Monterey) and 
I have done these, such as pull the latest from main and try to install after clearing out your node_modules folder
but is not worked
