### ISSUE TITLE
classnames is missing from package.json

### ISSUE THREAD

**Issue by JustinTime42** [ipfs/ipfs-webui#1976]
**Describe the bug**
I installed ipfs-webui. When I ran npm start, it threw the bug "couldn't resolve 'classnames' in components/button/Button.js"

**To Reproduce**
1. run npm start
2. observe the above error message

**Expected behavior**
The react app should launch with no errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Brave

**Resolution**
I manually installed classnames and that fixed the problem.

**Comment by SgtPooki** [comment]
We will look into this very soon, thanks for submitting the issue

**Comment by SgtPooki** [comment]
merged
