### ISSUE TITLE
[ipfs-geoip] failed to get and parse Data via ipfs.object.get('Qm*******') 

### ISSUE THREAD

**Issue by SmarticoApps** [ipfs/ipfs-webui#1992]
Compiled latest repo of IPFS WebUI
https://github.com/ipfs/ipfs-webui/

Ubuntu 20.04.4 LTS
Node version 16.12.0
NPM version 8.1.0

WebUI works on remote IPFS Node; connecting to Private IPFS swarm.

Adds files successfully via the WebUI and they appear on all IPFS nodes.

`http://5.161.121.x:3000/#/peers`  shows all 7 peers; but location for all nodes is UNKNOWN

Error in console:

```
index.js:32 [ipfs-geoip] failed to get and parse Data via ipfs.object.get('QmQe6m4QRo*******w1cS4nAux75iZqG4') TimeoutError: Request timed out
    at error.js:42:16
(anonymous) @ index.js:32
```

It repeats this error 7 times for all 7 peers

No custom modifications made to any source code.

**Comment by lidel** [comment]
@SmarticoApps which version of ipfs-webui are you using (it should be listed in bottom left corner)?

geoip database was updated in https://github.com/ipfs/ipfs-webui/pull/1958 and was released in v2.16.0

**Comment by SmarticoApps** [comment]
[UI v2.17.3]
(https://github.com/ipfs/ipfs-webui/releases/tag/v2.17.3)

**Comment by lidel** [comment]
@SmarticoApps thank you. This version did not ship with ipfs-desktop / Kubo yet, so the number of people who have updated geoip dataset (#1958) may explain why you have trouble finding some of its blocks.

I am closing this, as this should improve after more people  start co-hosting the dataset, and filled https://github.com/ipfs-shipyard/ipfs-geoip/issues/91 for tracking upstream fix.

As a workaround, you may want to  preload entire geoip database via `ipfs dag stat QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4` (note: it is ~380 MiB in size: `Size: 399424326, NumBlocks: 224986`)

**Comment by SmarticoApps** [comment]
Thanks. I'm on a private IPFS network; is that why it doesnt sync from the co-hosted dataset?

**Comment by SmarticoApps** [comment]
When I run that command, the command line remains blank for several hours with no feedback

`root@cluster1:~# ipfs dag stat QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4

`

**Comment by lidel** [comment]
Ah, yes. If you are in a private IPFS network, your node won't be able to fetch data from the public one.

You can work around by doing `ipfs dag export QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4 > geoip.car` on Public node, and then import geoip dataset via `ipfs dag import geoip.car`

**Comment by SmarticoApps** [comment]
```
root@cluster0:~/ipfs-update# ipfs dag export QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4 > geoip.car
 0s  0 B / ? [---------------------------------------------------------------------------------------------------------=]
 Error: block was not found locally (offline): ipld: could not find QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4 (currently offline, perhaps retry after attaching to the network)
root@cluster0:~/ipfs-update#
```

**Comment by aschmahmann** [comment]
> Error: block was not found locally (offline): ipld: could not find QmQe6m4QRoKk4Q7gxGMkUfanmtC4zgw1cS4nAux75iZqG4 (currently offline, perhaps retry after attaching to the network)

As the error mentions your node is offline, run the daemon and try again
