### ISSUE TITLE
Improve UX of IPNS publishing

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1993]
Now that we've added basic UI for publishing CIDs to IPNS (#1973) :partying_face: 
it may be a good time to go an extra mile and refine the UI.

Namely, I feel we could improve presentation of key names and CIDs (right now it is a bland monospace font).
Perhaps we could also add one-line explainer to the first modal (imagine user clicking "Publish to IPNS" and not knowing what it is):

Below is the current state:  

| Before Publishing |  Published | 
| ---- | ---- |
|  ![2022-07-26_14-37](https://user-images.githubusercontent.com/157609/181007655-bd81e465-5653-4c8d-aad7-efd3a5e677bd.png) | ![2022-07-26_14-35](https://user-images.githubusercontent.com/157609/181007656-e8bc48aa-054b-4785-bf1c-29319b6fb520.png) |

any ideas are welcome, cc @juliaxbow @hacdias

**Comment by hacdias** [comment]
Two thoughts:

- Make the monospace font surrounded by some box with some padding and round borders. The box would have a "copy" icon that would copy the CID/IPNS Key to the clipboard.
- Make the IPNS Key clickable with either `href=ipns://key` or `href=defaultPublicGateway/ipns/key`.

**Comment by juliaxbow** [comment]
- +1 hacdias's suggestion for a copy icon (or even "copy"). Could look something like:

<img width="915" alt="Screen Shot 2022-07-26 at 9 58 56 AM" src="https://user-images.githubusercontent.com/58958327/181066409-73d234dc-a1ed-440d-b522-acd06eba978c.png">
OR
<img width="819" alt="Screen Shot 2022-07-26 at 9 56 05 AM" src="https://user-images.githubusercontent.com/58958327/181066405-b4378851-0eed-4c81-afe1-cc12334cb60b.png">

- Then I would recommend changing the bottom right button to "Done" or "Finish" (unless there are more steps afterwards?) to indicate that IPNS publishing steps are complete at this stage

**Comment by lidel** [comment]
I like the idea of separating Done and Copy link. :+1:  

@hacdias interested in applying these before you start phasing out GUI activities?

**Comment by hacdias** [comment]
@lidel done #1998 :) Not yet 100% sure I'll leave GUI, but we'll see.

**Comment by Winterhuman** [comment]
@lidel @hacdias I noticed all the IPNS pull requests and issues being merged, however, I don't see any IPNS related functionality in the WebUI. Am I missing something?

**Comment by Winterhuman** [comment]
Nevermind, just realised it's because https://github.com/ipfs/ipfs-webui/issues/1965 and other P0 issues are still open and preventing a WebUI release, ignore me
