### ISSUE TITLE
Error: cannot view files

### ISSUE THREAD

**Issue by JFrayR** [ipfs/ipfs-webui#1994]
I have uploaded some documents to ipfs and my colleagues cannot see any file in my hash or in the link.

I was hoping you could see my files.

please help!

**Screenshots**
![error ipfs](https://user-images.githubusercontent.com/107519280/181403471-1df917fe-07ae-4785-9eb9-394e8efa564f.png)
![ipfs desktop](https://user-images.githubusercontent.com/107519280/181403473-e68cc92c-d1f8-4ea3-b5d8-ed6797f5c3e2.png)

**Desktop (please complete the following information):**
 -Windows 10 enterprise 
 - Browser [chrome, brave]

**Comment by RawNatural** [comment]
I have this exact same issue.

It's fine with old images. But any new image gets this 504 gateway time-out

**Comment by lidel** [comment]
This repository is about GUI interface used by ipfs-desktop. 
The problem you describe lies outside ipfs-webui: a public gateway is  unable to fetch data from your machine. Make sure the CID is provided to the network by a node that is publicly dialable, or pin it to a remote service that does the providing for you (see [this tutorial](https://docs.ipfs.tech/how-to/work-with-pinning-services/#use-an-existing-pinning-service)).

In the future, please use https://discuss.ipfs.tech/c/help/13 for general help like that.
