### ISSUE TITLE
Can't use cmd 

### ISSUE THREAD

**Issue by ZhangPeibin** [ipfs/ipfs-webui#2001]
**Describe the bug**
I can't use cmd to use ipfs command and I already install ipfs desktop
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hacdias** [comment]
IPFS Desktop no longer provides the IPFS command line utilities.

To install the IPFS CLI, please follow: https://docs.ipfs.tech/how-to/command-line-quick-start/
