### ISSUE TITLE
Add pinning service providers to default list

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-webui#2004]
We need to add pinning service providers that have compliance checks https://github.com/ipfs-shipyard/pinning-service-compliance

- [ ] Crust - https://github.com/ipfs/ipfs-webui/pull/1854 (currently blocked)
- [x] Filebase - https://github.com/ipfs/ipfs-webui/pull/2012
- [x] Estuary
- [x] Web3.storage - https://github.com/ipfs/ipfs-webui/pull/2025
- [ ] Nft.storage ?

**Comment by SgtPooki** [comment]
Pinged estuary and web3.storage about adding them. Waiting for acknowledgement before adding (Estuary pinning service is still invite only AFAIK, so I want to make sure they approve prior to being added to the default list)

**Comment by dchoi27** [comment]
Yes, would be great for web3.storage to get added! Thanks for thinking of us :)

**Comment by SgtPooki** [comment]
@dchoi27 FYI that the PR is out. See #2025.

**Comment by SgtPooki** [comment]
Got the "okay" from cake, but need a 42x42 image or SVG from them
