### ISSUE TITLE
webui.ipfs.io is not updated to the latest version

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#2021]
Seems we have a regression, publishing v2.18.0 did not update DNSLink at https://webui.ipfs.io:

- https://github.com/ipfs/ipfs-webui/releases/tag/v2.18.0
- https://webui.ipfs.io (is still v2.15.1)

**Comment by BigLep** [comment]
@SgtPooki : how do we prevent this from happening in the future and catch if it does?

**Comment by SgtPooki** [comment]
@BigLep it should have already been caught. I must have broken something with the release updates that I've done over the past month or two. The release workflow for v2.18.0 is at https://github.com/ipfs/ipfs-webui/actions/runs/3025892693

**Comment by SgtPooki** [comment]
Yep, it looks like I missed an if statement in the ci.yml workflow: 
https://github.com/ipfs/ipfs-webui/blob/fe4ef000ff087cb64c335182b17d2140e4f6ba01/.github/workflows/ci.yml#L138-L148

If you look at dev.webui.ipfs.io, it's updated with the latest commit: https://github.com/ipfs/ipfs-webui/commit/fe4ef00, but the prod DNSlink was not updated; the step itself was just skipped.

**Comment by SgtPooki** [comment]
After https://github.com/ipfs/ipfs-webui/pull/2024 is merged, we won't run into this issue again

**Comment by lidel** [comment]
@SgtPooki I think there is no point in spending time on manual fix.
Better do a patch release (i merged https://github.com/ipfs/ipfs-webui/pull/2019)  and smoke test fix from https://github.com/ipfs/ipfs-webui/pull/2024

**Comment by SgtPooki** [comment]
running ci.yml: https://github.com/ipfs/ipfs-webui/actions/runs/3048111224

**Comment by SgtPooki** [comment]
webui.ipfs.io is showing https://github.com/ipfs/ipfs-webui/commit/5e59065 as the latest revision.
