### ISSUE TITLE
UX improvements for import status pop-up window

### ISSUE THREAD

**Issue by juliaxbow** [ipfs/ipfs-webui#2030]
Not urgent but I have a few suggestions to improve UX/UI on the the import status pop-up. 

1. Open IPFS webui
2. Go to "Files"
3. Upload a file (via import or drag + drop)
4. See upload status pop-up window

UI issues/Suggestions (4 total): 
1. The exit and minimize buttons are not vertically center aligned (see screenshot with added lines for present state)
<img width="1003" alt="Icon alignment" src="https://user-images.githubusercontent.com/58958327/191821054-1ec6909e-8dda-4654-87d1-e2bd9cb4b631.png">

2. The arrow icon should be flipped to indicate state, i.e. minimized vs maximized (see gif for proposal) 
3. For better ux, the minimize button’s clickable area size should be increased. Ideally, the full title bar should be clickable and allow the user to minimize/maximize the pop-up (see gif for proposal) 
![import_status_minimize](https://user-images.githubusercontent.com/58958327/191821567-d466eda0-2cc3-4a3e-b284-caff35c2d1db.gif)

4. The stroke around the clickable area size for both exit and minimize buttons is unnecessary (see screenshot for present state)
<img width="967" alt="button stroke" src="https://user-images.githubusercontent.com/58958327/191821238-bef3f0de-5bef-4452-91b9-881fbe8a40a9.png">

**Comment by lidel** [comment]
sgtm, i'd say these are UX bugs that should be fixed :)
