### ISSUE TITLE
Webui not correctly linking to local gateway when running over LAN at .local domain

### ISSUE THREAD

**Issue by chrisguida** [ipfs/ipfs-webui#2031]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
# ipfs version --all
Kubo version: 0.15.0
Repo version: 12
System version: arm64/linux
Golang version: go1.18.5
```

### Config
`# ipfs config show`
```json
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "https://djnofp2u5mvjsewk7anxsj4iep3n5uvez362lek4ixjysgeefk5esxyd.local", #api/webui domain
        "http://localhost:3000",
        "http://127.0.0.1:5001",
        "https://webui.ipfs.io",
        "http://ipfs.embassy:5001",
        "https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local", #gateway domain
        "https://0.0.0.0:8080"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": true,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": {
      "localhost": null,
      "rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local": {
        "Paths": [
          "/ipfs",
          "/ipns"
        ]
      }
    },
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWPCNH8gBqGuuCxerv3wLEjBEEWHYJXxa8eUcsNSjLS6cm"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {
      "Enabled": true
    },
    "RelayService": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  },
  "Transports": {
    "Network": {
      "Relay": true
    }
  }
}
```

### Description

I am trying to package IPFS for [embassy-os](https://github.com/Start9Labs/embassy-os). See [this discussion forum post](https://discuss.ipfs.tech/t/cannot-access-gateway-over-mdns-local/15199) for some background on embassy-os.

1) Run `kubo` v0.15.0 in a docker container on a raspberry pi on my home network using https://github.com/chrisguida/ipfs-wrapper. The Dockerfile here is pretty much the same as the Dockerfile included in the `kubo` repo, with some slight modifications to adapt it to .
2) configure `kubo` as in [this entrypoint](https://github.com/chrisguida/ipfs-wrapper/blob/master/docker_entrypoint.sh).
3) In the webui, go to the "Files" tab and select any file to view it. The `ipfs.io` public gateway sometimes displays the file after a long wait. Other times, if I open the browser console I can see this error:

<img width="647" alt="Screen_Shot_2022-09-20_at_3 05 31_PM" src="https://user-images.githubusercontent.com/7445670/191531046-a1bc89eb-ec3d-48cb-b5ce-64648330be1f.png">

(As you can see, the browser does not like that the request to `http://0.0.0.0:8080` is cleartext HTTP, while the domain I'm viewing the webui through is HTTPS ("https://djnofp2u5mvjsewk7anxsj4iep3n5uvez362lek4ixjysgeefk5esxyd.local" in the above example config). Actually, I'm not even sure what `http://0.0.0.0:8080` is supposed to me. I do know that if I run `kubo` locally on my laptop, this request succeeds. How firefox is able to resolve this URL, ever, is beyond me.)

But since the point of embassy-os is to self-host, we want to avoid "public" gateways and use the gateway on our own device, which responds much faster anyway. If I go to the webui "Settings" tab and enter in my gateway address ("https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local" in the example config) into the "public gateway" field, clicking on files now works, and sends the files through my local gateway properly.

Issue ipfs/kubo#1: I would like to be able to configure this setting programmatically, ie in `docker_entrypoint.sh`. Requiring the user to manually find their gateway domain and input it into this settings field adds a lot of friction to the UX. However, that can be worked around for now if it's the only way. The real bug is below:

Issue ipfs/kubo#2: When I click "Download" on any file, *even after manually setting the gateway in the webui*, the browser still requests `http://0.0.0.0:8080`, rather than the local gateway I've configured. This of course results in an error. This makes it so that the user cannot download a file through the UI. The bizarre thing is that if I manually alter the download URL to replace `http://0.0.0.0:8080` with the local gateway URL ("https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local" in the example config), the file can be viewed through the browser just fine. For some reason, the webui is unable to simply link the user directly to the local gateway, *even when it is specifically configured in the webui*.

It's possible I'm missing a config value somewhere, as I'm fairly new to `kubo`, but this definitely seems like at least a documentation issue, and probably a bug in the webui.

Please let me know how I can help debug/fix this, as our community is asking for access to IPFS on embassy-os!

Thanks in advance,

--Chris

**Comment by chrisguida** [comment]
@lidel thanks so much for the response! I will work through this next week and get back to you :)

**Comment by lidel** [comment]
I think it would be useful for you to describe your use case. What is the end user experience you are designing for?

FWIW it is perfectly fine to run IPFS  Node, or even HTTP Gateway in your LAN.

What is tricky is to provide secure access to RPC port (and GUI like ipfs-webui).
That is admin-level, and allows changing node config, and as I said, was designed only for localhost access.
As long you take care of securing RPC access (e.g., via basic auth + TLS or something like that), it should be fine, but we do not have tests for non-localhot setups, and who knows what can break over time for your users if you go this route. 

SSH is the best solution IMO, because it removes surface for footguns, 

> Does this mean that using two different domains for the API and Gateway will not work? I can put them on the same domain if so.

No, I don't think you need same domain or port, technically it should work (even `localhost:8080` (gateway) and `localhost:5001/webui` (rpc api) are distinct origins), but you need the additional setup I mentioned.

> we need to access the .local domain over HTTPS, and the webui is using http; that is one of the problems that we need to fix or work around

Ah.. right.  Sadly Kubo's HTTP is designed as a backend service: it is listening on cleartext HTTP ports 8080 and 5001: they do not provide TLS or anything fancy like that, it is just HTTP 1.1.  Kubo does not support listening on HTTPS, for that you need to put some reverse proxy like Nginx or Caddy in front of it to correctly terminate TLS.  
So `Addresses.Gateway` set to `0.0.0.0` is fine, it will listen on all interfaces provided to your docker container.
I think you already have TLS termination set up correctly, too. 

Unfortunately, Kubo won't be able to listen on the final TLS address, so ipfs-webui will never be able to use the correct one.

> It appears as though the webui does not allow dialing an address that kubo itself cannot dial. Is this correct? 

Yes, `Addresses.Gateway` from Kubo config is the limiter here.

> If so, I think this is the feature that needs to be added, and as I mentioned previously, I'm willing to put in the work to add this feature if you guys would accept a PR that does this.


Are we talking about changing  ipfs-webui or Kubo? 

I would be open to review a PR  (remember to @lidel me) against ipfs-webui that is addressing (4) – it sounds like a generic  bug on Files screen. If `Addresses.Gateway` is offline/unreachable, then the public gateway from Settings should be used. 

I also could see how passing static API and Gateway addresses via URL  (`https://webui.local/?rpc=&localGw=&pubGw=`) that  reads them from URL and stores  in `window.localStorage`  could be useful for projects like https://github.com/ipfs-shipyard/go-ipfs-desktop   – not sure if this is useful to you tho.

If you had other fix in mind, lmk.

As for (5), this is unlikely.. Kubo bending backwards just for ipfs-webui. Changing existing behavior is unacceptable as it will lead to silent errors that are annoying to debug, especially in cloud contexts. 

If anything, we could add a separate setting, just like we have [`AppendAnnounce`](https://github.com/ipfs/kubo/blob/master/docs/config.md#addressesappendannounce) for libp2p listeners, and update ipfs-webui to also check that.
But if it is a dead setting (not used by Kubo itself) that is only used  by ipfs-webui it is.. a hard sell. 

I think what we could add to Kubo is a list of preferred public gateways – we need it for unrelated, but already planned work described in https://github.com/ipfs/kubo/issues/9159 – if that lands,  ipfs-webui could opportunistically read this list and use it too.

Lmk if you were successful with any of the paths discussed. 
We are working under constraints here, but should figure something out :)

**Comment by chrisguida** [comment]
Reporting back with some rest results:

I've tried using an array of strings instead of a string (potential solution number 3), and as expected that does not work, since Kubo cannot dial the .local address:

`Error: serveHTTPGateway: manet.Listen(/dns4/ipfsgw.local/tcp/443) failed: listen tcp4: lookup ipfsgw.local: no such host`

So potential solution number 3 is a no-go.

I've also tried forwarding port 8080 from the container to the host like so (potential solution number 2):

`socat tcp-l:8080,fork,reuseaddr tcp:ipfs.embassy:8080`

Then I set `Addresses.Gateway` like so:

`ipfs config --json Addresses.Gateway '["/ip4/172.18.0.1/tcp/8080", "/ip4/0.0.0.0/tcp/8080"]'`

and also simply:

`ipfs config --json Addresses.Gateway '"/ip4/172.18.0.1/tcp/8080"'`

But still got a "cannot listen" error:

`Error: serveHTTPGateway: manet.Listen(/ip4/172.18.0.1/tcp/8080) failed: listen tcp4 172.18.0.1:8080: bind: cannot assign requested address`

This was attempted before and after activating the `socat` tunnel. So potential solution number 2 is a no-go.

For the record, the `socat` command above does cause the embassy's IP address, at port 8080, to properly return the file when requested via a browser on the local network. So, again, this is simply a case of Kubo/ipfs-webui artificially restricting the user's access to certain addresses.

The SSH tunnel (potential solution number 1) works, I can confirm:

`ssh -L 127.0.0.1:8080:ipfs.embassy:8080 -L 127.0.0.1:5001:ipfs.embassy:5001 start9@embassy-<id>.local`

This forwards both the API and Gateway to `localhost`. As mentioned this would only be accessible to our advanced users, but at least it works.

**Comment by chrisguida** [comment]
>I think it would be useful for you to describe your use case. What is the end user experience you are designing for?

Basically embassy-os consists of an OS and a marketplace of open source software that has been packaged for said OS, not unlike apt, but without the need for the user to touch the command line ever, and without non-service packages; that is to say, all our packages are some kind of self-hostable server software, like bitcoin, lightning, mastodon, synapse, gitea, ghost, vaultwarden, filebrowser, etc. [Here's](https://marketplace.start9.com/) what we currently have on offer, though this collection is rapidly expanding. Any software that can be self-hosted and is open source can be packaged as an "app" for embassy-os (including IPFS of course). Our users are fanatics about privacy and digital independence, and love hosting their own data.

In addition to this, the services we host are designed to require no upfront configuration on the part of the user. They can simply navigate to the marketplace, click "install", then "configure", hit "save", then "start", and the service will set itself up and a health check will alert the user when the service is ready, for example, to visit in a browser (if it has a ui). Then they hit "launch ui" and they're using the service. No command line is required, and indeed no configuration is required. Of course the user can configure their service in any way that the package is designed to be configured (by the service package dev).

Every service is given either a system-generated .local address (for clearnet LAN access) or .onion address (for onion-routed remote access), or both.

We have over 1,000 users now ([see our telegram channel](https://t.me/start9_labs)), and a large number are eager to start running IPFS on their nodes, with 24/7 uptime, to aid the IPFS network, and also to be able to host, pin, and access their files privately over their own local gateways. IMHO, IPFS could benefit a lot from designing with this use case in mind.

>FWIW it is perfectly fine to run IPFS Node, or even HTTP Gateway in your LAN.

I definitely agree!

>What is tricky is to provide secure access to RPC port (and GUI like ipfs-webui).
That is admin-level, and allows changing node config, and as I said, was designed only for localhost access.
As long you take care of securing RPC access (e.g., via basic auth + TLS or something like that), it should be fine, but we do not have tests for non-localhot setups, and who knows what can break over time for your users if you go this route.

Yes, we are considering adding a reverse proxy with basic auth to the container. This would work better as a feature in the webui itself, but I'll see if we can get it done. Adding a reverse proxy to IPFS has been somewhat of a challenge for me so far.

>SSH is the best solution IMO, because it removes surface for footguns,

It's not ideal for us because we emphasize that our users won't need to touch the command line, and our users are used to services being plug-and-play with no additional setup required.

>No, I don't think you need same domain or port, technically it should work (even localhost:8080 (gateway) and localhost:5001/webui (rpc api) are distinct origins), but you need the additional setup I mentioned.

Ok great, thanks

>Ah.. right. Sadly Kubo's HTTP is designed as a backend service: it is listening on cleartext HTTP ports 8080 and 5001: they do not provide TLS or anything fancy like that, it is just HTTP 1.1. Kubo does not support listening on HTTPS, for that you need to put some reverse proxy like Nginx or Caddy in front of it to correctly terminate TLS.
So Addresses.Gateway set to 0.0.0.0 is fine, it will listen on all interfaces provided to your docker container.
I think you already have TLS termination set up correctly, too.

Yes, we have a reverse proxy in the OS that takes care of TLS, but it seems like we may need to add another reverse proxy inside the IPFS container to handle auth. Though the API/webui will still only be visible over lan, and over .onion as a Tor hidden service, neither of which will be accessible by the public. But adding auth will definitely make things more secure.

>Unfortunately, Kubo won't be able to listen on the final TLS address, so ipfs-webui will never be able to use the correct one. 

>Yes, Addresses.Gateway from Kubo config is the limiter here.

Yes, that is what it looks like. Unfortunate indeed.

>Are we talking about changing ipfs-webui or Kubo?

Whichever you think is more appropriate. It seems as though the webui should be able to respect the client "public gateway" settings, because as I mentioned previously, it already does this for "click to view", but not for "download". This actually just seems like a bug in the webui, and seems like the least invasive fix for this issue.

But, if you think the Go code needs to be modified to separate Kubo's listening address from the webui's connect address, then I'll do that. That also seems likely to be doable in the webui code. The fact that Kubo cannot listen on an address that it itself cannot connect to just seems.. wrong. But I'm new to this codebase so I'm not aware of all the reasons why the design was left that way, so perhaps they were good reasons.

>I would be open to review a PR (remember to @lidel me) against ipfs-webui that is addressing (4) – it sounds like a generic bug on Files screen. If Addresses.Gateway is offline/unreachable, then the public gateway from Settings should be used.

Yes, this seems like the place that makes most sense for us to start.

>I also could see how passing static API and Gateway addresses via URL (https://webui.local/?rpc=&localGw=&pubGw=) that reads them from URL and stores in window.localStorage could be useful for projects like https://github.com/ipfs-shipyard/go-ipfs-desktop – not sure if this is useful to you tho.

Yes, this seems like it could be useful.

>As for (5), this is unlikely.. Kubo bending backwards just for ipfs-webui. Changing existing behavior is unacceptable as it will lead to silent errors that are annoying to debug, especially in cloud contexts.

Again, this strikes me as a design flaw in Kubo. This behavior really makes it seem like this reference IPFS node implementation was not designed with running a on server device (separate from the client it is accessed from) in mind, which seems antithetical to IPFS's mission. Doesn't IPFS *want* people to run nodes in as many configurations as possible, so that there can be as many nodes as possible? Doesn't that make the data stored on IPFS that much more uncensorable? And isn't censorship resistance the whole point of IPFS?

>If anything, we could add a separate setting, just like we have [AppendAnnounce](https://github.com/ipfs/kubo/blob/master/docs/config.md#addressesappendannounce) for libp2p listeners, and update ipfs-webui to also check that.
But if it is a dead setting (not used by Kubo itself) that is only used by ipfs-webui it is.. a hard sell.

This sounds like it would work! Let me know if this is what I should do.

>I think what we could add to Kubo is a list of preferred public gateways – we need it for unrelated, but already planned work described in https://github.com/ipfs/kubo/issues/9159 – if that lands, ipfs-webui could opportunistically read this list and use it too.

Also a great suggestion! I'm down to work on whatever solution you think is best, as long as it helps onboard as many of our users to IPFS as we can :)

>Lmk if you were successful with any of the paths discussed.
We are working under constraints here, but should figure something out :)

Posted earlier with my test results, I didn't find any optimal solutions to the problem.

I really appreciate your being here, it means a lot! I'm sure we'll come up with something that works for everyone :)

**Comment by chrisguida** [comment]
Ok so I just realized that the IPFS Companion browser extension possibly fixes this. I was using it before and then it stopped working. I removed it and re-added it to my browser and now everything works, as long as I set the local gateway and toggle on "use local gateway". Will continue testing and report back!

**Comment by chrisguida** [comment]
Ok never mind, enabling IPFS Companion fixes the "download" behavior, but breaks the "click to view" behavior xD

Will see if there's some combination of webui and companion settings that fixes this.
