### ISSUE TITLE
Enabling WebTransport in Kubo v0.16.0-rc1 breaks Status page

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#2033]
## How to reproduce 

1. Run Kubo v0.16.0-rc1
2. Enable WebTransport by 
   1. adding `"/ip4/0.0.0.0/udp/4002/quic/webtransport"` to `Addresses.Swarm`
   2. enabling transport via `ipfs config Swarm.Transports.Network.WebTransport --json true`
3. Restart node
4. Open webui

See Release Notes for more info: https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.16.md

## Broken state

>   ![2022-09-27_15-22](https://user-images.githubusercontent.com/157609/192538694-274312d9-7994-4b98-8b8f-adbf7882ef4e.png)

## Suspected cause 

Guess: `ipfs.id` output breaks the way we present ADDRESSES on the Status page.
I see ipfs-webui in infinite loop trying to read `/api/v0/id` over and over again.

New type of addresses is now returned as part of `Addresses` list, values look like this:

```
"/ip4/47.22.210.45/udp/55918/quic/webtransport/certhash/uEiAkH5a4DPGKUuOBjYw0CgwjvcJCJMD2K_1aluKR_tpevQ/certhash/uEiAfbgiymPP2_nX7Dgir8B4QkksjHp2lVuJZz0F79Be9JA/p2p/12D3KooWBdmLJjhpgJ9KZgLM3f894ff9xyBfPvPjFNn7MKJpyrC2"
```
cc https://github.com/ipfs/kubo/issues/9237
@SgtPooki or @hacdias  will you have time to take a look? Ideally we would fix this and ship new ipfs-webui and update Kubo  0.16 ships.

**Comment by SgtPooki** [comment]
repro: 
![image](https://user-images.githubusercontent.com/1173416/192596111-be849c2c-c76a-4b38-b842-7a48f2dffa0e.png)

**Comment by SgtPooki** [comment]
```
err:  Error: no protocol with name: webtransport
    at Protocols (protocols-table.js:15:1)
    at stringToStringTuples (codec.js:45:1)
    at stringToBytes (codec.js:182:1)
    at Object.fromString (codec.js:190:1)
    at __webpack_modules__../node_modules/multiaddr/src/index.js.withIs.proto.className (index.js:46:1)
    at new <anonymous> (index.js:40:1)
    at __webpack_modules__../node_modules/multiaddr/src/index.js.withIs.proto.className (index.js:29:1)
    at index.js:40:1
    at id.js:24:1
    at Array.map (<anonymous>)
```

**Comment by SgtPooki** [comment]
Looks like the line throwing is https://github.com/multiformats/js-multiaddr/blob/7efd9b62d52db2b9464ec32f606819e3598657e9/src/protocols-table.ts#L82

**Comment by SgtPooki** [comment]
attempted a quick fix but was unsuccessful:

https://github.com/ipfs/ipfs-webui/commit/fc939b708fd76d4fc23eab49077db73a3d216b75 results in an error

https://github.com/ipfs/ipfs-webui/commit/98587cb9abf2608a358a366548ea7b9d0ccbe0b6 results in another error:
```
Failed to get identity Error: invalid character 'u' in 'uEiD1qy_pwUXrusX6CufD-gipAzNSz52OVOhJUUOLpmmMNw'
    at Base.decode (base.js:43:1)
    at fromString (from-string.js:51:1)
    at Function.convertToBytes [as toBytes] (convert.js:84:1)
    at codec.js:97:1
    at Array.map (<anonymous>)
    at stringTuplesToTuples (codec.js:91:1)
    at stringToBytes (codec.js:183:1)
    at Object.fromString (codec.js:190:1)
    at __webpack_modules__../node_modules/multiaddr/src/index.js.withIs.proto.className (index.js:46:1)
    at new <anonymous> (index.js:40:1)
```

**Comment by lidel** [comment]
https://github.com/multiformats/js-multiaddr/pull/271 was missing tests for `/webtransport/certhash/../certhash/..`  (addr format announced by Kubo 0.16.0-rc1)
 
 I've added them in https://github.com/multiformats/js-multiaddr/pull/276 but code from multiaddr@11  parses it correctly, so this looks like a problem on ipfs-webui's  end (ancient dependencies).

**Comment by BigLep** [comment]
What's the verdict here?  Are we going to do more hacks, or just this as more forcing function to get the dependencies updated... ?

**Comment by SgtPooki** [comment]
> What's the verdict here? Are we going to do more hacks, or just this as more forcing function to get the dependencies updated... ?

@BigLep This is going to require dependency updates.. hacks aren't really going to work without those hacks bleeding into older dependency versions that don't require those hacks in the newest versions. It's most likely less work to update webui than try to figure out a working hack

**Comment by BigLep** [comment]
@SgtPooki : ACK.  One more thing dependent on the dependency update project!  Let's add it to the issue to put further weight on the criticality of that work.  Thanks.

**Comment by lidel** [comment]
Just flagging this is a hard blocker for having WebTransport enabled by default in Kubo.

**Comment by SgtPooki** [comment]
@marten-seemann per our discussion, see https://github.com/ipfs/ipfs-webui/issues/2033#issuecomment-1259939882

We can dive into this deeper at your convenience
