### ISSUE TITLE
Playing a media (audio/video) stops after a few seconds

### ISSUE THREAD

**Issue by nlko** [ipfs/ipfs-webui#2080]
**Describe the bug**
When playing an audio or a video file (locally hosted in my case), it stops after a few seconds (less than 20 seconds) and the position in the stream is set to the beginning. It happen both in the web browser and the desktop application (appImage in my case).

I checked the network tab and noticed it stops playing when the browser send a REST POST : http://127.0.0.1:5001/api/v0/cat?arg=[HASH].

It seems that whenever it happens, the <audio></audio> is replaced in the DOM (and the music stops).

**To Reproduce**
1. Go to 'Files'
2. Import QmbGtJg23skhvFmu9mJiePVByhfzu5rwo74MEkVDYAmF5T as BigBunny.mov
3. Open the file the BigBunny.mov file
4. Press the play button

**Expected behavior**
It should be able to play without resetting (like before).

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome Version 108.0.5359.71 
 - WebUi Revision 04eb7b3

**Comment by SgtPooki** [comment]
@nlko thanks for submitting this issue. I was able to reproduce using a local webui on the latest on the main branch.

https://user-images.githubusercontent.com/1173416/212746349-0b0abfb5-3b71-4110-a150-c21b4b0a9386.mov

We will mark this as a bug and look into this.

**Comment by JustinTime42** [comment]
I experience this issue as well. 
If it's a helpful clue, the same thing happens for other types of files, it just isn't really noticeable with images and such. But that POST request happens exactly every 30 seconds while that file preview screen is open.

**Comment by JustinTime42** [comment]
@SgtPooki I think I see the culprit here:
`FilesList.js` receives `pins` as a prop. In `pinning.js` `intervalFetchPins()` runs every 30 seconds, and when it does, it updates the pins, triggering a re-render. 
I'm not familiar enough with that part of the codebase to understand why it needs to fetch the pins on a repeating schedule, but a solution could be to either not run that function repeatedly or reworking how FilesList receives that data so that it doesn't re-render with those updates.

**Comment by SgtPooki** [comment]
@JustinTime42 this was updated back when @hacdias did a refactor of the remote pinning logic and status updates. I believe we still need to poll remote pinning services to check for new pins, but there are specific cases where we shouldn't be re-rendering (from specific to more generic):

1. playing a video
2. previewing an exact file
3. viewing a page that does not have a list of files that might be pinned.
