### ISSUE TITLE
My IPFS is too much slow

### ISSUE THREAD

**Issue by Igno22** [ipfs/ipfs-webui#2112]
I don't know so much about this world, but I don't understand why my IPFS is so slow: about 3 weeks ago I loaded some files on it for an automatic loading on OpenSea, but appears the "content is not available yet" message. I contacted OpenSea support and they say it could be the IPFS which is not able to recover metadata (json) files. Someone help me please, I don't know what to do to get out from this situation.

**Comment by SgtPooki** [comment]
@Igno22 Thanks for reporting the issues you're having with using IPFS. It seems like this is more related to IPFS in general and may be better as a post on our discuss forums at [discuss.ipfs.tech](https://discuss.ipfs.tech/tags/c/help/13/ipfs-desktop). 

I've no experience with OpenSea, but you will likely find folks who are on our discussion forums.
