### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zbg-ft** [ipfs/ipfs-webui#2115]
![image](https://github.com/ipfs/ipfs-webui/assets/62411209/8e1b33b9-56bd-4163-911a-8010265197fc)

![image](https://github.com/ipfs/ipfs-webui/assets/62411209/2f799304-185d-446d-868f-4ca72ddb2c25)

**Comment by SgtPooki** [comment]
related to https://github.com/ipfs/ipfs-webui/issues/2118
