### ISSUE TITLE
ipfs is not recognized in Windows Terminal

### ISSUE THREAD

**Issue by g-adel** [ipfs/ipfs-webui#2144]
**Describe the bug**
For some reason, after installing IPFS Desktop to run for a few hours for the first time, which was working, I returned to it not working anymore with the error "Could not connect to the IPFS API". My problem isn't this in particular (after restarting it worked again) my problem was that when I followed the on-screen instructions of opening the Windows Terminal and typing `ipfs daemon` only to be greeted with `ipfs : The term 'ipfs' is not recognized as the name of a cmdlet`. I'm guessing this is because IPFS is not registered in my system variables or something. I looked around a bit but couldn't find anything. 

**To Reproduce**

1. Install and run IPFS Desktop on Windows.
2. After running for a few hours, leave and then return to find an error saying "Could not connect to the IPFS API".
3. As per on-screen instructions, open the Windows Terminal and type ipfs daemon.
4. Notice the error ipfs : `The term 'ipfs' is not recognized as the name of a cmdlet.`

**Expected behavior**
IPFS should be working in Windows terminal out of the box with IPFS Desktop

Desktop (please complete the following information):
 - OS: Windows 10
 - Version a43dd23

**Comment by j-maffe** [comment]
To add to this, I'm not even sure how I can add IPFS to PATH. I found the directory `\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe` but with adding that path to the system variables I still can't access IPFS from the terminal.
