### ISSUE TITLE
Big black cross on Peers section of IPFS Desktop.

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-webui#2146]
**Describe the bug**
I was using it and from nowhere a big black cross appeared in the peers section.

**To Reproduce**

**Expected behavior**
See the peers.

**Screenshots**
![Screenshot_3](https://github.com/ipfs/ipfs-webui/assets/13344308/2b3b670c-e587-41c7-853a-e393620bff2b)

![hkhjkjjjj](https://github.com/ipfs/ipfs-webui/assets/13344308/18d391c3-670d-49a2-8696-e8a6d508e4eb)

**Desktop (please complete the following information):**
 - OS: Windows 10
![Screenshot_5](https://github.com/ipfs/ipfs-webui/assets/13344308/ebe2fe94-d64c-40f7-b79a-a1a179d91897)

 - Browser FireFox
 - Version 116.0 (64-bit)

**Additional context**

**Comment by SgtPooki** [comment]
@ZeroCool22 Thanks for reporting this error. I've seen this infrequently when making code changes in ipfs-desktop. It's usually due to some uncaught error in one of the components on the peers page.

Can you please provide the [error logs](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files) so we can investigate further?

**Comment by ZeroCool22** [comment]
> @ZeroCool22 Thanks for reporting this error. I've seen this infrequently when making code changes in ipfs-desktop. It's usually due to some uncaught error in one of the components on the peers page.
> 
> Can you please provide the [error logs](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files) so we can investigate further?

[error.log](https://github.com/ipfs/ipfs-webui/files/12292603/error.log)

**Comment by gov360** [comment]
[error.log](https://github.com/ipfs/ipfs-webui/files/12538202/error.log)
I'm also having the same issue

**Comment by neongreen** [comment]
I saw the black cross yesterday after connecting to a VPN. I'm using IPFS Desktop 0.31.0, webui [2277a09](https://github.com/ipfs/ipfs-webui/commit/2277a09).

**Comment by leqord** [comment]
Seeing it on Kubo WebUi, OpenSuse Tumbleweed.
