### ISSUE TITLE
When we remove a file, the Blocks of that files must be deleted too?

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-webui#2147]
Using IPFS Desktop.

When someone **removes** the file from the IPFS Desktop, it should **remove/delete** the Block/s corresponding to that file inside the **.ipfs\blocks** folder too?

Also, when we have a lot of files and one to delete one of them lets, say, we don't have a way to know which Block belongs to that file, so we can delete only that blocks and not others corresponding to other files that we still want to be sharing.

![Screenshot_3](https://github.com/ipfs/ipfs-webui/assets/13344308/772af9ee-83af-4b7e-8045-8048180070cf)

Other way, our HDD/SDD will be filled up with files that we don't want to share anymore?

Sorry if i'm talking nonsense from my ignorance, but i think we need a way to identify **what blocks belong to what files**, so we can delete it safely without affecting the other files.

**Comment by SgtPooki** [comment]
@ZeroCool22 Thanks for submitting this question!

In general, you should not interact directly with the files/data in your .ipfs config directory except for `$HOME/.ipfs/config`. If you need to clear space and have removed the files from IPFS Desktop, you can run the garbage collector from the "advanced" menu in the system tray to remove them from your harddrive: 

![Image](https://github.com/ipfs/ipfs-webui/assets/1173416/20059e78-94e7-4a0f-8b94-66799424915a)

**NOTE:** This screenshot from macOS will look different than on Windows.

I think item #5 at https://discuss.ipfs.tech/t/how-does-ipfs-files-interact-with-pins/16685/2?u=sgtpooki may be able to help you with some more advanced things if you're interested.

Please let me know if there's a specific problem we can help with

**Comment by ZeroCool22** [comment]
Thx for the reply.

So, if we delete a file from the GUI Desktop, and then we run Garbage Collector it will delete that unused Blocks from the .ipfs\blocks?
