### ISSUE TITLE
Unexisting `files` directory shows in Files page

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-webui#2158]
**Describe the bug**

`files` directory shows on the top-level listing in `Files` section. This directory does not exist and it seems to be MFS root.

**To Reproduce**
1. Go to 'Files'
4. See directory

**Expected behavior**

It shouldn't show up.

**Screenshots**

<img width="1407" alt="image" src="https://github.com/ipfs/ipfs-webui/assets/5447088/8a597f46-3893-43d0-b2b4-ec32aed78e69">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Electron (IPFS Desktop)
 - Version:  95d468b
 
**Additional context**

The `files` directory seems to be my MFS root:

```sh
$ ipfs files ls -l
./	QmSz6L7WWJUp3JxgShRFkRsWsuxeMtxFmJ43teu75NWz7B	0
Preserved Pages/	QmduDsDMgnL4wMr2GNHtDEVzdVcEuHgJZwq4HTaPpibcqP	0
Quick dive.mp4	QmbA8Uw6LXEMtGiQr2X1RPRLT1hJMQnMHb9pd1HUnGftaK	75987806
```

**Comment by SgtPooki** [comment]
I do not see "files" in my files screen either, and am unable to run `ipfs files ls -l` due to some error:

```bash
> ipfs files ls -l
Error: unrecognized node type in cache node
```

but without `-l` works:

```bash
╰─ ✘ 1 ❯ ipfs files ls
2023-05-13-game.mp4
Asset 2.png
BugBunny.mov
IMG_0652.mov
IMG_0672.HEIC
IP-stewards-h2-planning-meeting-recording.car
RC Car exercise.MOV
Screenshot 2023-02-11 at 10.15.42 AM.png
UDMPro CenturyLink PPPoE.png
bigBuckBunny
filebase_padding.svg
gateway checker
ipfs-companion-imports
ipfs-geoip
multi-toggle-modal.png
stock_skateboarder.webm
test
w3up-delegation-api
xkcd
```
