### ISSUE TITLE
Share Link incorrectly gives path routed instead of subdomain routed URL.

### ISSUE THREAD

**Issue by MicahZoltu** [ipfs/ipfs-webui#2244]
- OS: Windows
- Version of IPFS Desktop: 0.32.0

**Describe the bug**
When you right click on a file in Files and choose "Share Link" you are given a URL like `https://<host>/ipfs/<cid>`.  This should be of the form `https://<cid>.ipfs.<host>` for security reasons.

**To Reproduce**
1. Go to Files tab.
2. Right click on any file.
3. Choose "Share Link"
4. Notice the link provided uses path routing.

**Expected behavior**
Subdomain routing is always used.

**Additional context**
Path routing is known to be insecure for websites that use cookies, local storage, etc.  This is well documented in the IPFS documentation and the documentation and security experts all recommend using subdomain routing whenever possible (which is almost always possible).  These share links are encouraging people to share URLs that are insecure by default, and we should instead be using subdomain by default.

**Comment by acul71** [comment]
@lidel Thank you for your detailed response.

I agree with your suggestion that "ipfs-webui should have something similar, with an extra check to decide which gateway to use based on the shared CID." I'll proceed in this direction.

Thanks for the guidance!

**Comment by acul71** [comment]
@lidel @SgtPooki 
> > Are the labels ok?
> 
> I think the labels are decent, but they feel a little too similar. Maybe we need a disclaimer saying that certain content that doesn't need origin-isolation for the subdomain gateway input.

The strategy here is to always use the public subdomain gateway (dweb.link) and use the public path gateway (ipfs.io) as a fallback in case the CID v1 length is > 63 chars
Is this ok?

**Comment by acul71** [comment]
@lidel @SgtPooki 
https://github.com/acul71/ipfs-webui-fork/pull/1

**Comment by lidel** [comment]
@acul71 are you using AI or some GUI tools? That PR makes no sense (it merges from `main` in this repo  to a branch in your repo, and changes described in PR description are not in git).

What you want to do is to open PR from your form into this repository.

**Comment by acul71** [comment]
@lidel 
Sorry did submit too late in the night....
Thanks is this ok:
https://github.com/ipfs/ipfs-webui/pull/2255
