### ISSUE TITLE
webui spawning helia and failing to establish libp2p webtransport connections

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#2250]
For some reason webui makes.. libp2p webtransport requests? 

> ![2024-08-30_21-55](https://github.com/user-attachments/assets/63ffe920-9bd9-4be6-9192-c1a0251f9d3b)

Last time I worked on ipfs-webui, we did not run libp2p node, everything was delegated over HTTP RPC To Kubo. 

We really don't want this, especially in ipfs-desktop, which runs webui all the time in the background

**Comment by lidel** [comment]
@SgtPooki any ideas where does this Helia init come from? ipld explorer? is it running DHT Client? `ec2-54-205-137-251.compute-1.amazonaws.com`  does not look like one of our boxes?

**Comment by SgtPooki** [comment]
Helia is in ipld explorer but it shouldnt be doing any server/providing work

**Comment by SgtPooki** [comment]
I can look deeper in a few hours

**Comment by lidel** [comment]
@SgtPooki we either need a flag that can be passed from  ipfs-webui to skip helia init entirely, or at least initialize it without js-libp2p.

**Comment by SgtPooki** [comment]
@lidel I am not seeing webtransport/libp2p in webui when ran locally, nor in ipld-explorer-components. Do you have a cached service-worker from service-worker-gateway running on the same origin you ran ipfs-webui on?

**Comment by lidel** [comment]
@SgtPooki I can reproduce on both firefox and chromium, below is vanilla google chrome and http://127.0.0.1:5001/webui/ from Kubo 0.30.0-rc2 (but the same is in 0.29.0) – somehting tries to diall bootstrappers over `wss://`

> ![2024-09-05_19-46](https://github.com/user-attachments/assets/e613c2e2-77a5-42dc-bdee-af932d61723e)

**Comment by SgtPooki** [comment]
FYI it looks like webui was still on an old version because of auto release issues we ran into previously

https://github.com/ipfs/ipld-explorer-components/releases/tag/v7.0.0 is the newest release that contains migration to @helia/http. 

ipfs-webui is still on an old version: https://github.com/ipfs/ipfs-webui/blob/eefae250ff57a19cc16808a1ec31e74f4b826b3f/package.json#L70
