### ISSUE TITLE
Explore page: stop sending requests to remote HTTP servers

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#2266]
> this is remaining part of regression initially identified in https://github.com/ipfs/ipfs-webui/issues/2250

## Bug

Explore page triggers block and delegated routing request to remote HTTP servers, including ones outside of control of IPFS project.

> ![2024-09-17_14-32](https://github.com/user-attachments/assets/ce446934-939d-4697-973f-88d3a790c7a3)

This is bad because it does not leverage local gateway, wastes bandwidth, and leaks IPs and CIDs to third party servers, which is extra bad in private cluster contexts.

## Expected behavior

Only the local Kubo RPC and Gateway should be used when IPLD Explorer is used in ipfs-webui.

- There should not be any delegated `/routing/v1` calls (local gateway will take care of routing, no need for doing it in JS over the internet)
- The block requests `?format=raw` should only go to localhost gateway (like we do for file previews)

**Comment by lidel** [comment]
@SgtPooki found this after testing latest main branch with https://github.com/ipfs/ipfs-webui/issues/2250 merged, preferably we would fix this and then tag a release to close the privacy leak for private swarm users. 

(fine to pick it up after you are back from JS week, we just want to include it in Kubo 0.31 https://github.com/ipfs/kubo/issues/10499)

**Comment by SgtPooki** [comment]
@lidel explorer components should only be calling remote gateways if it's enabled: https://github.com/ipfs/ipld-explorer-components/blob/cad6b454ec83940dea86ee1bfb20c415ce9efd18/src/lib/init-helia.ts#L20-L40

I think we can just add a `localStorage.setItem('explore.ipld.gatewayEnabled', false)` in ipfs-webui to disable this behavior for webui

**Comment by lidel** [comment]
@SgtPooki tried that, but then nothing works. feels like there needs to be another setting which only uses specific gateway (webui would pass localhost one) and does not use delegated routing.

**Comment by SgtPooki** [comment]
@lidel if you set the following localStorage config, does it fetch from the local gateway??

```js
localStorage.setItem('kuboGateway', JSON.stringify({ port: '8080', trustlessBlockBrokerConfig: { init: { allowLocal: true, allowInsecure: true }}}))
```

**Comment by lidel** [comment]
@SgtPooki yep, seems to do the trick, but it works only if page is reloaded to apply new helia setting (so i guess we need to set this before helia init):

> ![2024-09-23_22-22](https://github.com/user-attachments/assets/08b6697c-1b57-4c1c-aa93-eeffe99dbfbb)

> ![2024-09-23_22-22_1](https://github.com/user-attachments/assets/0515d4a0-ccd5-4cc0-9869-d6952bedcc55)

**Comment by SgtPooki** [comment]
ok I wanted to make sure it worked for you.. so we don't need ipld-explorer-component changes, just default localStorage changes for folks. PR incoming
