### ISSUE TITLE
Bloated CAR file

### ISSUE THREAD

**Issue by rmlearney-digicatapult** [ipfs/ipfs-webui#2300]
**Describe the bug**
All previous releases had CAR files around 28-36MB in size. Current CAR file (v4.4.0 which removed unnecessary stuff) is now 120MB!

**To Reproduce**
Information on this repo

**Expected behavior**
CAR file should be around the same size as previous versions or explanation provided

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Using local IPFS deployment in test environment. Have had to work-around by pinning old version of IPFS in docker images rather than using main release branch.

**Comment by lidel** [comment]
Fixed in https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.1 (CAR is back to ~27MiB)
