### ISSUE TITLE
Stats - time to discover and transfer new cids to the gateway and their respective dag size

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-webui#841]
> "do we have metrics on "time to discover and transfer new hashes to the gateway and their respective dag size? this would be a cool stat for the WebUI as well, which means that the ipfs-api should have a way to get stats from Gateway specific things."

@diasdavid

**Comment by lidel** [comment]
cc @kyledrake – I think we have some sorts of stats for gateways already as a prior art (?)
