### ISSUE TITLE
Optimize CountryChart widget on Status Page

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#848]
I am quite sure the moment we ship it officially, someone will ask us this, so let's be proactive and try to answer why a simple looking Status page in webui:

-  makes [1k of requests and fetches around 6MB in about a minute](https://user-images.githubusercontent.com/157609/46475718-94f09380-c7e6-11e8-8c74-b6ad49c96ab7.png) :upside_down_face: 
   - intuitively this feels off for a simple status page
- left open, continues to eat bandwidth at the steady rate:
  - ~5 minutes later: ![~2k and 20MB in 5 minutes](https://user-images.githubusercontent.com/157609/46475874-f87ac100-c7e6-11e8-904a-3fa45c35dfb4.png)
  - ~10 minutes later: ![2018-10-04--15-18-54](https://user-images.githubusercontent.com/157609/46476613-e7cb4a80-c7e8-11e8-915c-5f1f144b8308.png)

Size does not concerns me as much as the number of HTTP requests.
Looks like [multiple calls to `ipfs.object.get`](https://user-images.githubusercontent.com/157609/46476828-69bb7380-c7e9-11e8-9b3a-5e2fca5f1ba0.png) happen always after refreshing peer list.
What are we fetching? Is it geodata or something else? 

Is there anything we could do about it? 
Optimize or preload geo data (or use smaller db with countries only)? 
Throttle the number of parallel API calls? Decrease refresh interval, improve caching? 
There is a ceiling on how many parallel HTTP requests make sense.

**Comment by olizilla** [comment]
I believe this is geodata. If you disable the peer-locations bundle and the peer locations graph on the status page, does the behaviour change?

**Comment by lidel** [comment]
@olizilla yup, that was it. I [removed CountryChart](https://user-images.githubusercontent.com/157609/46481058-c53e2f00-c7f2-11e8-93dd-f7a2e6c6ba03.png) and load dropped to <100 requests in first minute:

- ![2018-10-04--16-29-45](https://user-images.githubusercontent.com/157609/46481072-cff8c400-c7f2-11e8-89fc-121705d68032.png)

**Comment by olizilla** [comment]
Personally, I'm not super comfortable with the bandwidth use, but I feel like this is a learned response from building centralised web apps, and trying to optimise away as many http requests as possible.

So this is a perception issue; after the first usage, most of that data will have been cached in your IPFS node, so in practice, the bandwidth is all localhost (ignoring more elaborate remote set ups). 

I totally agree that this doesn't change the fact that people are going to be surprised by it. Perhaps it turns into a positive, once we explain that it's all local traffic, not wider network traffic, becuase, you know, content-addressing.

Perhaps a way to visualise and explain the gap between "traffic between page and api" and "traffic between node to peers" could help too.

**Comment by olizilla** [comment]
so our options are

- disable the widget and only geolocate when on the peers page (not great)
- geolocate more slowly, but this will still amount to the same total traffic shown in the network tab, just more slowly. (meh)
- see if we can re-encode ipfs-geoip to be more compact (probably a few days work)

All of which aren't ideal, is there some rad solution I'm missing?

**Comment by lidel** [comment]
We could make `CountryChart` a "click to play"  thing.
Eg. display text (+some icon) "Which countries my node connects to?" , when clicked, loads the widget.
Not sure if it is better than just geolocating slowly. 

> I totally agree that this doesn't change the fact that people are going to be surprised by it. Perhaps it turns into a positive, once we explain that it's all local traffic, not wider network traffic, becuase, you know, content-addressing.

I think this is probably the way we should frame it for now.

**Comment by olizilla** [comment]
looking at this the first thing that jumps out at me is why does the situation not improve after the second run. Is my swarm really changing so much that I'm cache-missing all of the previously resolved things? Then there is the even more surprising issue of, why are content-addressed get requests to the api not just being pulled from the browser cache... well, because the API doesn't return any cache headers.

<img width="1050" alt="screenshot 2018-10-18 09 51 17" src="https://user-images.githubusercontent.com/58871/47143059-40581880-d2bc-11e8-98b7-8fb47224cb24.png">

There is an issue from 2016:  https://github.com/ipfs/go-ipfs/issues/3543

I have a new crusade!

**Comment by olizilla** [comment]
**Background**
- go-ipfs has been setting cache-control: immutable on the gate for quite some time, and is name checked on the mozhacks article https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/
- https://github.com/ipfs/go-ipfs/pull/3870 - Gateway has `cache-control: immutable` for files but not directories

There is the interesting question of whether an api request should ever really be considered immutable... we may change the semantics of the api, and the structure of the response. That could be countered by incrementing the api version number in the path, but we've not done that so far, so I'd imagine there would work to do to formalise the process. Or put another way, if we add immutable headers to api responses, we'll have to increment the api version number if we do change it, which sounds reasonable.

**Comment by olizilla** [comment]
@lidel in the meantime let's just dial the concurrency of the peer-location lookups right down to 1. It chills everything out a bit without significantly reducing the experience of the graph and the peers page.

**5min**
![screenshot 2018-10-18 11 27 36](https://user-images.githubusercontent.com/58871/47148633-1ce79a80-d2c9-11e8-92e6-dcfcc551332f.png)

The heavy request is repeatedly getting the peers list, which is ~90KB for me with ~700 peers, so that and the bandwidth stats api would be good candidates for proposing a streaming / ws based api.

**Comment by lidel** [comment]
@olizilla sounds like a sensible mitigation for now :+1: 
Regarding `cache-control: immutable` in API responses, I added some thoughts in https://github.com/ipfs/go-ipfs/issues/3543#issuecomment-431166289

**Comment by Mikaela** [comment]
For me bandwidth usage by IPFS is mostly between 10 kB/s, with long staring sometimes jumping to 500 kB/s, but when I open the webui I start seeing at least 10 Mb/s download traffic which is 1/5 of promised bandwidth and makes sites load slowly and my connectivity not work very well in general.

I had a lot of Firefox tabs open including webui when I noticed this issue, I resolved it by stopping the ipfs daemon entirely and was linked here from #ipfs on freenode.

I am running `--routing=dhtclient` as I understood it's recommended for decreasing bandwidth usage and this node isn't very useful for being only direcltly reachable over IPv6 and [Yggdrasil-network](https://yggdrasil-network.github.io/). `ipfs version 0.4.18` installed with `ipfs-updater` on Debian GNU/Linux testing (buster).

**Comment by lidel** [comment]
Thank you @Mikaela, this is very useful feedback.

@olizilla I feel CountryChart is still skewing stats bit too much, causing more harm than good. 

To be specific: we really don't want our "_traffic stats screen_" to skew "traffic stats" by an order of magnitude, it paints a picture of IPFS being "bandwidth heavy". 

What if we start planning to:

- Move CountryChart widger to Peers screen
- Visualize different stats in its place, eg. Repo space usage 
  (Or something else that does not require geodata. If we are missing APIs, this is a good venue for requesting them)

?

**Comment by olizilla** [comment]
Yep. We don't want the act of observing to radically alter your nodes behaviour. In general, we need to fix the related issue documented here https://github.com/ipfs/go-ipfs/issues/5613

In the meantime, moving the peer location work to the peers page seems wise.

**Comment by olizilla** [comment]
I think we could solve this by removing the CountryChart component and replacing it with a file-drop area for quickly adding files to IPFS. That seems like a nice feature to have quick access to from the home page.

**Comment by SgtPooki** [comment]
Closing this as resolved.
