### ISSUE TITLE
File listing does not refresh after file rename

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#996]
**Describe the bug**
Renaming file does not refresh UI and old name stays until an action is performed:

**To Reproduce**

1. Go to Files
2. Rename one via checkbox + bottom menu
3. File listing won't update
4. Uncheck  the file, name will finally refresh

**Expected behavior**

File listing should be refreshed after file renames.

**Screenshots**

> ![Peek 2019-03-20 13-44](https://user-images.githubusercontent.com/157609/54685144-593c5280-4b16-11e9-9cef-d6d088617970.gif)

**Desktop):**
 - OS: Linux
 - Browser: Firefox 65
 - Web UI Version: v2.4.4

**Comment by olizilla** [comment]
@fsdiogo i know you had this working recently, can you take another look.

**Comment by olizilla** [comment]
nudge @fsdiogo

**Comment by fsdiogo** [comment]
This has worked before, but after moving to the react-virtualized files list the logic is not the same and not so straightforward to fix.

I'll have a look ASAP.
