### ISSUE TITLE
GET http://127.0.0.1:5001/ipfs/QmXc9raDM1M5G5fpBnVyQ71vR4gbnskwnB9iMEzBuLgvoZ/locales/en/translation.json 404 (Not Found)

### ISSUE THREAD

**Issue by hklcf** [ipfs/ipfs-webui#997]
![image](https://user-images.githubusercontent.com/410302/55007464-6a0b2d80-501a-11e9-93fc-6f1527aa048d.png)

**Comment by fphammerle** [comment]
I have a very similar issue:
The WebUI tries to load `http://localhost:5001/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/locales/en-US/translation.json`.
However, the `locales` folder does not contain `en-US`.

```sh
$ curl -v http://localhost:5001/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/locales/en-US/translation.json
[...]
< HTTP/1.1 404 Not Found
< Date: Mon, 22 Apr 2019 09:47:36 GMT
< Content-Length: 176
< Content-Type: text/plain; charset=utf-8
ipfs resolve -r /ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub/locales/en-US/translation.json: no link named "en-US" under QmXySugWDTxYr45JojxCtQmcm3Nvij7Tk79R4seBe5Pa6h
```

**Comment by achingbrain** [comment]
I see the same thing but with `en-GB`, I guess because that's what my browser locale is.

**Comment by lidel** [comment]
The [latest webui](https://github.com/ipfs/ipfs-webui/releases/latest) should cache locale info to avoid unnecessary requests such as `translation.json`
Some 404 are expected as it is a way of webui figuring out if a specific locale file exists.

**Comment by nonchip** [comment]
except the issue is that the [latest webui](webui.ipfs.io) doesn't do that, instead just dies before even rendering a single letter after it can't find `en-US` (because the folder's called `en`).
